import { REFUND_SCENERY_FILES } from './refund_scenery.js';
import { INDIA_FILES } from './india_assets.js';
import { MARKET_LIFE_FILES } from './delhi_life_market.js';
// assets.js - loads game-ready PNGs at boot; each degrades to null if missing.
// NOTE: assets/sources/* are reference-only and are never loaded here.
import { RS } from './engine.js';
import { packOfFile, track } from './loading.js';
import { assetURL } from './asset_url.js';

export const FILES = {
  ...INDIA_FILES,
  cl_screen_art:'assets/stages/refund_tower/closer/screens.png', // Reuse the illustrated world map inside the Scam King's live displays.
  ...REFUND_SCENERY_FILES,
  ...MARKET_LIFE_FILES,
  prop_delhi_ic_thela: 'assets/stages/dirty_delhi/cast/porter_cart.png',
  delhi_docker_wrench: 'assets/stages/dirty_delhi/cast/docker_wrench.png',
  electric_impact:'assets/fx/electric_impact.png',
  nr_vista_rural: 'assets/stages/night_train/rebuild/vista_rural.png',
  nr_vista_industry: 'assets/stages/night_train/rebuild/vista_industry.png',
  nr_vista_river: 'assets/stages/night_train/rebuild/vista_river.png',
  nr_vista_smoke: 'assets/stages/night_train/rebuild/vista_smoke.png',
  nr_chad_roof_climb: 'assets/stages/night_train/rebuild/chad_roof_climb.png',
  nr_roof_fittings: 'assets/stages/night_train/rebuild/roof_fittings.png',
  nr_neta_props: 'assets/stages/night_train/rebuild/neta_props.png',
  nr_office_chair: 'assets/stages/night_train/rebuild/office_chair.png',
  nr_office_desk_broken: 'assets/stages/night_train/rebuild/office_desk_broken.png',
  nr_office_desk: 'assets/stages/night_train/rebuild/office_desk.png',
  nr_conductor_intro: 'assets/stages/night_train/rebuild/conductor_intro.png',
  nr_office: 'assets/stages/night_train/rebuild/office.png',
  nr_station_life: 'assets/stages/night_train/rebuild/station_life.png',
  nr_finale_approach_sky: 'assets/stages/night_train/rebuild/finale_approach_sky.png',
  nr_finale_approach_station: 'assets/stages/night_train/rebuild/finale_approach_station.png',
  nr_finale_approach_track: 'assets/stages/night_train/rebuild/finale_approach_track.png',
  nr_finale_approach_platform: 'assets/stages/night_train/rebuild/finale_approach_platform.png',
  nr_finale_approach_clouds: 'assets/stages/night_train/rebuild/finale_approach_clouds.png',
  nr_finale_sky: 'assets/stages/night_train/rebuild/finale_sky.png',
  nr_finale_station: 'assets/stages/night_train/rebuild/finale_station.png',
  nr_finale_track: 'assets/stages/night_train/rebuild/finale_track.png',
  nr_finale_platform: 'assets/stages/night_train/rebuild/finale_platform.png',
  nr_finale_passenger_damage: 'assets/stages/night_train/rebuild/finale_passenger_damage.png',
  // Escape finale at gameplay scale (tools/production/build_train_finale_escape.py).
  nr_finale_chad: 'assets/stages/night_train/rebuild/finale_chad.png',
  nr_finale_neta_blast: 'assets/stages/night_train/rebuild/finale_neta_blast.png',
  nr_finale_blast: 'assets/stages/night_train/rebuild/finale_blast.png',
  nr_finale_fire: 'assets/stages/night_train/rebuild/finale_fire.png',
  nr_finale_debris: 'assets/stages/night_train/rebuild/finale_debris.png',
  nr_finale_dust: 'assets/stages/night_train/rebuild/finale_dust.png',
  nr_finale_notes: 'assets/stages/night_train/rebuild/finale_notes.png',
  nr_finale_dynamite: 'assets/stages/night_train/rebuild/finale_dynamite.png',
  nr_finale_smoke: 'assets/stages/night_train/rebuild/finale_smoke.png',
  nr_finale_car: 'assets/stages/night_train/rebuild/finale_car.png',
  nr_finale_bogie: 'assets/stages/night_train/rebuild/finale_bogie.png',
  nr_finale_coupling: 'assets/stages/night_train/rebuild/finale_coupling.png',
  nr_gangway: 'assets/stages/night_train/rebuild/gangway.png',
  nr_wreck: 'assets/stages/night_train/rebuild/wreck.png',
  nr_journey_vista: 'assets/stages/night_train/rebuild/journey_vista.png',
  arcade_fragments: 'assets/fx/arcade_fragments.png',
  // A family's own knockout debris, same 4x2 layout (fragments_<trainType>); others use the generic set.
  fragments_nr_paan: 'assets/fx/fragments/nr_paan.png',
  fragments_nr_tte: 'assets/fx/fragments/nr_tte.png',
  fragments_nr_brawler: 'assets/fx/fragments/nr_brawler.png',
  fragments_nr_commando: 'assets/fx/fragments/nr_commando.png',
  fragments_nr_rack: 'assets/fx/fragments/nr_rack.png',
  fragments_nr_chai: 'assets/fx/fragments/nr_chai.png',
  fragments_nr_captain: 'assets/fx/fragments/nr_captain.png',
  // Netaji's own debris for the Delhi finale, where blast 1 tears him apart (js/train_finale.js).
  fragments_nr_neta: 'assets/fx/fragments/nr_neta.png',
  fragments_ic_closer: 'assets/stages/refund_tower/scam_king/fragments.png',
  arcade_defeats: 'assets/fx/arcade_defeats.png',
  boxing_impacts: 'assets/fx/boxing_impacts.png',
  fx_punch: 'assets/fx/finisher_punch.png',
  fx_debris: 'assets/fx/finisher_debris.png',
  fx_gore: 'assets/fx/finisher_gore.png',
  shera_severed_head: 'assets/stages/night_train/neta/shera/severed_head.png',
  nr_passenger_reaction: 'assets/stages/night_train/rebuild/passenger_reaction.png',
  nr_passenger_seated: 'assets/stages/night_train/rebuild/passenger_seated.png',
  nr_station_tea: 'assets/stages/night_train/rebuild/station_tea.png',
  nr_st_family: 'assets/stages/night_train/rebuild/st_family.png',
  nr_st_worker: 'assets/stages/night_train/rebuild/st_worker.png',
  nr_st_guard: 'assets/stages/night_train/rebuild/st_guard.png',
  nr_st_reader: 'assets/stages/night_train/rebuild/st_reader.png',
  nr_st_sleeper: 'assets/stages/night_train/rebuild/st_sleeper.png',
  nr_st_porter: 'assets/stages/night_train/rebuild/st_porter.png',
  nr_st_crow: 'assets/stages/night_train/rebuild/st_crow.png',
  nr_st_queue_man: 'assets/stages/night_train/rebuild/st_queue_man.png',
  nr_st_queue_woman: 'assets/stages/night_train/rebuild/st_queue_woman.png',
  nr_st_fan: 'assets/stages/night_train/rebuild/st_fan.png',
  nr_st_freight_cars: 'assets/stages/night_train/rebuild/st_freight_cars.png',
  nr_st_fg_column: 'assets/stages/night_train/rebuild/st_fg_column.png',
  nr_st_fg_lantern: 'assets/stages/night_train/rebuild/st_fg_lantern.png',
  nr_st_fg_pillar: 'assets/stages/night_train/rebuild/st_fg_pillar.png',

  nr_platform_front: 'assets/stages/night_train/rebuild/platform_front.png',
  nr_join_yard_hall: 'assets/stages/night_train/rebuild/join_yard_hall.png',
  nr_join_hall_platform: 'assets/stages/night_train/rebuild/join_hall_platform.png',
  nr_join_hall_platform_front: 'assets/stages/night_train/rebuild/join_hall_platform_front.png',
  nr_vestibule: 'assets/stages/night_train/rebuild/vestibule.png',
  nr_chad_board: 'assets/stages/night_train/rebuild/chad_board.png',
  nr_locomotive: 'assets/stages/night_train/rebuild/locomotive.png',
  nr_floor_general_sleeper: 'assets/stages/night_train/rebuild/floor_general_sleeper.png',
  nr_floor_sleeper_pantry: 'assets/stages/night_train/rebuild/floor_sleeper_pantry.png',
  nr_floor_pantry_ac: 'assets/stages/night_train/rebuild/floor_pantry_ac.png',
  nr_floor_ac_private: 'assets/stages/night_train/rebuild/floor_ac_private.png',

  nr_private_damaged:'assets/stages/night_train/rebuild/private_damaged.png',
  nr_rural_near: 'assets/stages/night_train/rebuild/rural_near.png',
  nr_industry_near: 'assets/stages/night_train/rebuild/industry_near.png',
  nr_river_near: 'assets/stages/night_train/rebuild/river_near.png',

  nr_yard: 'assets/stages/night_train/rebuild/yard.png',
  nr_hall: 'assets/stages/night_train/rebuild/hall.png',
  nr_platform: 'assets/stages/night_train/rebuild/platform.png',
  nr_general: 'assets/stages/night_train/rebuild/general.png',
  nr_sleeper: 'assets/stages/night_train/rebuild/sleeper.png',
  nr_pantry: 'assets/stages/night_train/rebuild/pantry.png',
  nr_ac: 'assets/stages/night_train/rebuild/ac.png',
  nr_private: 'assets/stages/night_train/rebuild/private.png',
  nr_roof: 'assets/stages/night_train/rebuild/roof.png',
  nr_rural: 'assets/stages/night_train/rebuild/rural.png',
  nr_industry: 'assets/stages/night_train/rebuild/industry.png',
  nr_river: 'assets/stages/night_train/rebuild/river.png',
  nr_hatch_open: 'assets/stages/night_train/rebuild/hatch_open.png',
  nr_ticket_clerk: 'assets/stages/night_train/rebuild/ticket_clerk.png',
  nr_ticket_scanner: 'assets/stages/night_train/rebuild/ticket_scanner.png',
  nr_chad_entry: 'assets/stages/night_train/rebuild/chad_entry.png',
  nr_chad_cinema: 'assets/stages/night_train/rebuild/chad_cinema.png',
  nr_passengers: 'assets/stages/night_train/rebuild/passengers.png',
  nr_passengers_life: 'assets/stages/night_train/rebuild/passengers_life.png',
  nr_passengers_idle: 'assets/stages/night_train/rebuild/passengers_idle.png',
  nr_seated_life: 'assets/stages/night_train/rebuild/seated_life.png',
  nr_sari_life: 'assets/stages/night_train/rebuild/sari_life.png',
  nr_fixtures_hang: 'assets/stages/night_train/rebuild/fixtures_hang.png',
  nr_train_exterior: 'assets/stages/night_train/rebuild/train_exterior.png',
  chai_gob: 'assets/stages/night_train/rebuild/chai_gob.png',
  chai_puddle: 'assets/stages/night_train/rebuild/chai_puddle.png',
  chai_steam: 'assets/stages/night_train/rebuild/chai_steam.png',
  nr_conductor_suitcase: 'assets/stages/night_train/rebuild/conductor_suitcase.png',
  nr_conductor_wad: 'assets/stages/night_train/rebuild/conductor_wad.png',
  nr_conductor_stamp: 'assets/stages/night_train/rebuild/conductor_stamp.png',
  nr_conductor_box: 'assets/stages/night_train/rebuild/conductor_box.png',
  nr_conductor_box_open: 'assets/stages/night_train/rebuild/conductor_box_open.png',
  nr_conductor_hazards: 'assets/stages/night_train/rebuild/conductor_hazards.png',
  nr_conductor_planks: 'assets/stages/night_train/rebuild/conductor_planks.png',
  nr_conductor_notes: 'assets/stages/night_train/rebuild/conductor_notes.png',
  nr_conductor_chain_mount: 'assets/stages/night_train/rebuild/conductor_chain_mount.png',
  nr_conductor_chain_link: 'assets/stages/night_train/rebuild/conductor_chain_link.png',
  nr_conductor_chain_handle: 'assets/stages/night_train/rebuild/conductor_chain_handle.png',
  nr_platform_ladder: 'assets/stages/night_train/rebuild/platform_ladder.png',
  nr_explosion: 'assets/stages/night_train/rebuild/explosion.png',
  nr_gate: 'assets/stages/night_train/rebuild/gate.png',
  prop_nr_case: 'assets/stages/night_train/rebuild/prop_nr_case.png',
  prop_nr_case_b: 'assets/stages/night_train/rebuild/prop_nr_case_b.png',
  prop_nr_crate: 'assets/stages/night_train/rebuild/prop_nr_crate.png',
  prop_nr_crate_b: 'assets/stages/night_train/rebuild/prop_nr_crate_b.png',
  prop_nr_trolley: 'assets/stages/night_train/rebuild/prop_nr_trolley.png',
  prop_nr_trolley_b: 'assets/stages/night_train/rebuild/prop_nr_trolley_b.png',
  prop_nr_table: 'assets/stages/night_train/rebuild/prop_nr_table.png',
  prop_nr_table_b: 'assets/stages/night_train/rebuild/prop_nr_table_b.png',
  prop_nr_urn: 'assets/stages/night_train/rebuild/prop_nr_urn.png',
  prop_nr_urn_b: 'assets/stages/night_train/rebuild/prop_nr_urn_b.png',
  prop_nr_contraband: 'assets/stages/night_train/rebuild/prop_nr_contraband.png',
  prop_nr_contraband_b: 'assets/stages/night_train/rebuild/prop_nr_contraband_b.png',
  dialogue_frame: 'assets/ui/dialogue_frame.png',
  direction_arrow: 'assets/ui/direction_arrow.png',
  travel_elevator_cabin: 'assets/travel/elevator/elevator_cabin.png',
  travel_elevator_frame: 'assets/travel/elevator/elevator_frame.png',
  title_art: 'assets/ui/title_art.png',
  logo: 'assets/ui/logo.png',
  gs_emblem_l: 'assets/ui/gigastation/emblem_left.png',
  gs_emblem_r: 'assets/ui/gigastation/emblem_right.png',
  gs_wordmark: 'assets/ui/gigastation/wordmark.png',
  gs_ce: 'assets/ui/gigastation/computer_entertainment.png',
  gs_logo: 'assets/ui/gigastation/logo.png',
  gs_chad: 'assets/ui/gigastation/chad.png',
  go_sign: 'assets/ui/go_sign.png',
  style_d: 'assets/ui/style/d.png',
  style_c: 'assets/ui/style/c.png',
  style_b: 'assets/ui/style/b.png',
  style_a: 'assets/ui/style/a.png',
  style_s: 'assets/ui/style/s.png',
  style_ss: 'assets/ui/style/ss.png',
  style_sss: 'assets/ui/style/sss.png',
  portrait_chad: 'assets/ui/portrait_chad.png',
  results_portrait: 'assets/ui/results_portrait.png',
  results_badge: 'assets/ui/results_badge.png',
  results_card: 'assets/ui/results_card.png',
  portrait_chad_48: 'assets/ui/portrait_chad_48.png',
  portrait_raja: 'assets/ui/portrait_raja.png',
  portrait_thekedar: 'assets/ui/portrait_thekedar.png',

  bg_lair_wall: 'assets/lair/wall.png',
  bg_lair_floor: 'assets/lair/floor.png',
  lair_worldmap: 'assets/lair/worldmap.png',
  lair_hifi: 'assets/lair/hifi.png',
  lair_map_panel: 'assets/lair/map_panel.png',
  bg_lair_sky_far: 'assets/lair/sky_far.png',
  bg_lair_sky_near: 'assets/lair/sky_near.png',
  lair_bar_stools: 'assets/lair/bar_stools.png',
  lair_bar_bottles_top: 'assets/lair/bar_bottles_top.png',
  lair_bar_bottles_low: 'assets/lair/bar_bottles_low.png',
  lair_bar_drink_0: 'assets/lair/bar_drink_0.png',
  lair_bar_drink_1: 'assets/lair/bar_drink_1.png',
  lair_bar_drink_2: 'assets/lair/bar_drink_2.png',
  lair_bar_drink_3: 'assets/lair/bar_drink_3.png',
  lair_bar_drink_4: 'assets/lair/bar_drink_4.png',
  lair_humidor: 'assets/lair/humidor.png',
  lair_tankscape: 'assets/lair/tankscape.png',
  lair_tank_frame: 'assets/lair/tank_frame.png',
  lair_baitfish_0: 'assets/lair/baitfish_0.png',
  lair_baitfish_1: 'assets/lair/baitfish_1.png',
  lair_baitfish_2: 'assets/lair/baitfish_2.png',
  lair_baitfish_3: 'assets/lair/baitfish_3.png',
  lair_baitfish_b_0: 'assets/lair/baitfish_b_0.png',
  lair_baitfish_b_1: 'assets/lair/baitfish_b_1.png',
  lair_baitfish_b_2: 'assets/lair/baitfish_b_2.png',
  lair_baitfish_b_3: 'assets/lair/baitfish_b_3.png',
  lair_crab_0: 'assets/lair/crab_0.png',
  lair_crab_1: 'assets/lair/crab_1.png',
  lair_crab_2: 'assets/lair/crab_2.png',
  lair_crab_3: 'assets/lair/crab_3.png',
  lair_lounge_rug: 'assets/lair/lounge_rug.png',
  lair_lounge_chair: 'assets/lair/lounge_chair.png',
  lair_overmantel: 'assets/lair/overmantel.png',
  lair_bag_chain: 'assets/lair/bag_chain.png',
  lair_gloves: 'assets/lair/gloves.png',
  // the master suite: one generation per pose, chaining from sitting up to lying down
  lair_bed_0: 'assets/lair/bed_0.png',
  lair_bed_1: 'assets/lair/bed_1.png',
  lair_bed_2: 'assets/lair/bed_2.png',
  lair_bed_3: 'assets/lair/bed_3.png',
  lair_bed_4: 'assets/lair/bed_4.png',
  lair_bed_5: 'assets/lair/bed_5.png',
  lair_bed_6: 'assets/lair/bed_6.png',
  lair_bed_7: 'assets/lair/bed_7.png',
  // four frames: the logs hold still, the flames move
  lair_fender: 'assets/lair/fender.png',
  lair_fire_0: 'assets/lair/fire_0.png',
  lair_fire_1: 'assets/lair/fire_1.png',
  lair_fire_2: 'assets/lair/fire_2.png',
  lair_fire_3: 'assets/lair/fire_3.png',
  lair_bed_rug: 'assets/lair/bed_rug.png',
  lair_bed_wardrobe: 'assets/lair/bed_wardrobe.png',
  lair_bed_nightstand: 'assets/lair/bed_nightstand.png',
  lair_gym_plates: 'assets/lair/gym_plates.png',
  lair_gym_kettles: 'assets/lair/gym_kettles.png',
  lair_gym_curl: 'assets/lair/gym_curl.png',
  lair_gym_bench: 'assets/lair/gym_bench.png',
  lair_lounge_empty: 'assets/lair/lounge_empty.png',
  lair_lounge_smoke_0: 'assets/lair/lounge_smoke_0.png',
  lair_lounge_smoke_1: 'assets/lair/lounge_smoke_1.png',
  lair_lounge_smoke_2: 'assets/lair/lounge_smoke_2.png',
  lair_lounge_smoke_3: 'assets/lair/lounge_smoke_3.png',
  lair_lounge_smoke_4: 'assets/lair/lounge_smoke_4.png',
  lair_lounge_smoke_5: 'assets/lair/lounge_smoke_5.png',
  lair_lounge_smoke_6: 'assets/lair/lounge_smoke_6.png',
  // the lion (tools/production/build_lair_lion.py): one canvas, bottom-centre anchored
  lair_lion_bow_a: 'assets/lair/lion_bow_a.png',
  lair_lion_bow_a2: 'assets/lair/lion_bow_a2.png',
  lair_lion_bow_b: 'assets/lair/lion_bow_b.png',
  lair_lion_bow_c: 'assets/lair/lion_bow_c.png',
  lair_lion_lie: 'assets/lair/lion_lie.png',
  lair_lion_lie_lift: 'assets/lair/lion_lie_lift.png',
  lair_lion_r0: 'assets/lair/lion_r0.png',
  lair_lion_r1: 'assets/lair/lion_r1.png',
  lair_lion_r2: 'assets/lair/lion_r2.png',
  lair_lion_r3: 'assets/lair/lion_r3.png',
  lair_lion_r4: 'assets/lair/lion_r4.png',
  lair_lion_r5: 'assets/lair/lion_r5.png',
  lair_lion_r6: 'assets/lair/lion_r6.png',
  lair_lion_r7: 'assets/lair/lion_r7.png',
  lair_lion_r_land: 'assets/lair/lion_r_land.png',
  lair_lion_r_land2: 'assets/lair/lion_r_land2.png',
  lair_lion_r_land3: 'assets/lair/lion_r_land3.png',
  lair_lion_rise1: 'assets/lair/lion_rise1.png',
  lair_lion_rise1b: 'assets/lair/lion_rise1b.png',
  lair_lion_rise2: 'assets/lair/lion_rise2.png',
  lair_lion_sit: 'assets/lair/lion_sit.png',
  lair_lion_sit_front: 'assets/lair/lion_sit_front.png',
  lair_lion_sit_turn: 'assets/lair/lion_sit_turn.png',
  lair_lion_sit_up: 'assets/lair/lion_sit_up.png',
  lair_lion_stand: 'assets/lair/lion_stand.png',
  lair_lion_stand_sit: 'assets/lair/lion_stand_sit.png',
  lair_lion_stretch: 'assets/lair/lion_stretch.png',
  lair_lion_stretch_in: 'assets/lair/lion_stretch_in.png',
  lair_lion_stretch_lift: 'assets/lair/lion_stretch_lift.png',
  lair_lion_stretch_out: 'assets/lair/lion_stretch_out.png',
  lair_lion_stretch_up: 'assets/lair/lion_stretch_up.png',
  lair_lion_turn: 'assets/lair/lion_turn.png',
  lair_lion_turn_front: 'assets/lair/lion_turn_front.png',
  lair_lion_w0: 'assets/lair/lion_w0.png',
  lair_lion_w1: 'assets/lair/lion_w1.png',
  lair_lion_w2: 'assets/lair/lion_w2.png',
  lair_lion_w3: 'assets/lair/lion_w3.png',
  lair_lion_w4: 'assets/lair/lion_w4.png',
  lair_lion_w5: 'assets/lair/lion_w5.png',
  lair_lion_w6: 'assets/lair/lion_w6.png',
  lair_lion_w7: 'assets/lair/lion_w7.png',
  lair_lion_wake: 'assets/lair/lion_wake.png',
  lair_shark_0: 'assets/lair/shark_0.png',
  lair_shark_1: 'assets/lair/shark_1.png',
  lair_shark_2: 'assets/lair/shark_2.png',
  lair_shark_3: 'assets/lair/shark_3.png',
  // keyed by boss id, so js/hub.js can look one up straight off BOSSES
  trophy_train: 'assets/lair/trophies/train.png',
  trophy_train_detail: 'assets/lair/trophies/train-detail.png',
  trophy_delhi: 'assets/lair/trophies/delhi.png',
  trophy_delhi_detail: 'assets/lair/trophies/delhi-detail.png',
  trophy_refund: 'assets/lair/trophies/refund.png',
  trophy_refund_detail: 'assets/lair/trophies/refund-detail.png',
  lair_relic_raja: 'assets/lair/relic_raja.png',
  lair_relic_dredger: 'assets/lair/relic_dredger.png',
  lair_relic_neta: 'assets/stages/night_train/rebuild/relic_neta.png',
  lair_relic_sir: 'assets/lair/relic_sir.png',

  prop_bike: 'assets/story/motorcycle/bike.png',
  prop_crate: 'assets/props/crate.png',
  prop_crate_b: 'assets/props/crate_b.png',
  prop_matka: 'assets/props/matka.png',
  prop_matka_b: 'assets/props/matka_b.png',
  prop_tyres: 'assets/props/tyres.png',
  prop_tyres_b: 'assets/props/tyres_b.png',
  prop_table: 'assets/props/table.png',
  prop_table_b: 'assets/props/table_b.png',
  prop_sign: 'assets/props/sign.png',
  prop_sign_b: 'assets/props/sign_b.png',
  prop_cart: 'assets/props/cart.png',
  prop_cart_b: 'assets/props/cart_b.png',
  prop_bag: 'assets/props/bag.png',
  // DIRTY DELHI
  prop_drum: 'assets/props/drum.png',
  prop_drum_b: 'assets/props/drum_b.png',
  prop_mithai: 'assets/props/mithai.png',
  prop_mithai_b: 'assets/props/mithai_b.png',
  prop_thelapole: 'assets/props/thelapole.png',
  prop_thelapole_b: 'assets/props/thelapole_b.png',
  prop_dhobislab: 'assets/props/dhobislab.png',
  prop_dhobislab_b: 'assets/props/dhobislab_b.png',
  // THE NIGHT TRAIN

};

export const ASSETS = Object.fromEntries(Object.keys(FILES).map((k) => [k, null]));

// Everything is authored at RS device pixels per logical px.
const LOGICAL_SCALE = new Set();

// One pack (js/loading.js), or every file when no pack is named.
export function loadAssets(pack) {
  return Promise.all(Object.entries(FILES).filter(([key, src]) => !pack || packOfFile(key, src) === pack)
    .map(([key, src]) => track(packOfFile(key, src), new Promise((resolve) => {
      const img = new Image();
      img.onload = () => { img._as = LOGICAL_SCALE.has(key) ? 1 : RS; ASSETS[key] = img; resolve(); };
      img.onerror = () => { ASSETS[key] = null; resolve(); };
      img.src = assetURL(src);
    }))));
}
