// assets.js - loads game-ready PNGs at boot; each degrades to null if missing.
// NOTE: assets/ai/* are reference-only and are never loaded here.
import { RS } from './engine.js';

export const FILES = {
  title_art: 'assets/title_art.png',
  logo: 'assets/logo.png',
  ending_art: 'assets/ending_art.png',
  go_sign: 'assets/go_sign.png',
  portrait_chad: 'assets/portrait_chad.png',
  portrait_chad_48: 'assets/portrait_chad_48.png',
  portrait_raja: 'assets/portrait_raja.png',
  bg_lair_wall: 'assets/bg_lair_wall.png',
  bg_lair_floor: 'assets/bg_lair_floor.png',
  lair_worldmap: 'assets/lair/worldmap.png',
  lair_hifi: 'assets/lair/hifi.png',
  lair_map_panel: 'assets/lair/map_panel.png',
  bg_lair_sky_far: 'assets/bg_lair_sky_far.png',
  bg_lair_sky_near: 'assets/bg_lair_sky_near.png',
  lair_bar_stools: 'assets/lair/bar_stools.png',
  lair_bar_bottles_top: 'assets/lair/bar_bottles_top.png',
  lair_bar_bottles_low: 'assets/lair/bar_bottles_low.png',
  lair_bar_drink_0: 'assets/lair/bar_drink_0.png',
  lair_bar_drink_1: 'assets/lair/bar_drink_1.png',
  lair_bar_drink_2: 'assets/lair/bar_drink_2.png',
  lair_bar_drink_3: 'assets/lair/bar_drink_3.png',
  lair_bar_drink_4: 'assets/lair/bar_drink_4.png',
  lair_humidor: 'assets/lair/humidor.png',
  lair_tankscape: 'assets/lair/tankscape.png',
  lair_tank_frame: 'assets/lair/tank_frame.png',
  lair_baitfish_0: 'assets/lair/baitfish_0.png',
  lair_baitfish_1: 'assets/lair/baitfish_1.png',
  lair_baitfish_2: 'assets/lair/baitfish_2.png',
  lair_baitfish_3: 'assets/lair/baitfish_3.png',
  lair_baitfish_b_0: 'assets/lair/baitfish_b_0.png',
  lair_baitfish_b_1: 'assets/lair/baitfish_b_1.png',
  lair_baitfish_b_2: 'assets/lair/baitfish_b_2.png',
  lair_baitfish_b_3: 'assets/lair/baitfish_b_3.png',
  lair_crab_0: 'assets/lair/crab_0.png',
  lair_crab_1: 'assets/lair/crab_1.png',
  lair_crab_2: 'assets/lair/crab_2.png',
  lair_crab_3: 'assets/lair/crab_3.png',
  lair_lounge_rug: 'assets/lair/lounge_rug.png',
  lair_lounge_chair: 'assets/lair/lounge_chair.png',
  lair_overmantel: 'assets/lair/overmantel.png',
  lair_bag_chain: 'assets/lair/bag_chain.png',
  lair_gloves: 'assets/lair/gloves.png',
  // the master suite: one generation per pose, chaining from sitting up to lying down
  lair_bed_0: 'assets/lair/bed_0.png',
  lair_bed_1: 'assets/lair/bed_1.png',
  lair_bed_2: 'assets/lair/bed_2.png',
  lair_bed_3: 'assets/lair/bed_3.png',
  lair_bed_4: 'assets/lair/bed_4.png',
  lair_bed_5: 'assets/lair/bed_5.png',
  lair_bed_6: 'assets/lair/bed_6.png',
  lair_bed_7: 'assets/lair/bed_7.png',
  // four frames: the logs hold still, the flames move
  lair_fender: 'assets/lair/fender.png',
  lair_fire_0: 'assets/lair/fire_0.png',
  lair_fire_1: 'assets/lair/fire_1.png',
  lair_fire_2: 'assets/lair/fire_2.png',
  lair_fire_3: 'assets/lair/fire_3.png',
  lair_bed_rug: 'assets/lair/bed_rug.png',
  lair_bed_wardrobe: 'assets/lair/bed_wardrobe.png',
  lair_bed_nightstand: 'assets/lair/bed_nightstand.png',
  lair_gym_plates: 'assets/lair/gym_plates.png',
  lair_gym_kettles: 'assets/lair/gym_kettles.png',
  lair_gym_curl: 'assets/lair/gym_curl.png',
  lair_gym_bench: 'assets/lair/gym_bench.png',
  lair_lounge_empty: 'assets/lair/lounge_empty.png',
  lair_lounge_smoke_0: 'assets/lair/lounge_smoke_0.png',
  lair_lounge_smoke_1: 'assets/lair/lounge_smoke_1.png',
  lair_lounge_smoke_2: 'assets/lair/lounge_smoke_2.png',
  lair_lounge_smoke_3: 'assets/lair/lounge_smoke_3.png',
  lair_lounge_smoke_4: 'assets/lair/lounge_smoke_4.png',
  lair_lounge_smoke_5: 'assets/lair/lounge_smoke_5.png',
  lair_lounge_smoke_6: 'assets/lair/lounge_smoke_6.png',
  lair_tiger_lie: 'assets/lair/tiger_lie.png',
  lair_tiger_wake: 'assets/lair/tiger_wake.png',
  lair_tiger_sit: 'assets/lair/tiger_sit.png',
  lair_tiger_stretch: 'assets/lair/tiger_stretch.png',
  lair_tiger_snarl: 'assets/lair/tiger_snarl.png',
  lair_tiger_0: 'assets/lair/tiger_0.png',
  lair_tiger_1: 'assets/lair/tiger_1.png',
  lair_tiger_2: 'assets/lair/tiger_2.png',
  lair_tiger_3: 'assets/lair/tiger_3.png',
  lair_tiger_4: 'assets/lair/tiger_4.png',
  lair_tiger_5: 'assets/lair/tiger_5.png',
  lair_tiger_6: 'assets/lair/tiger_6.png',
  lair_tiger_7: 'assets/lair/tiger_7.png',
  lair_shark_0: 'assets/lair/shark_0.png',
  lair_shark_1: 'assets/lair/shark_1.png',
  lair_shark_2: 'assets/lair/shark_2.png',
  lair_shark_3: 'assets/lair/shark_3.png',
  // keyed by boss id, so js/hub.js can look one up straight off BOSSES
  lair_relic_raja: 'assets/lair/relic_raja.png',
  bg_bazaar_v2_wall: 'assets/stages/bazaar_v2/wall.png',
  bg_bazaar_v2_floor: 'assets/stages/bazaar_v2/floor.png',
  bg_d1_wall: 'assets/stages/dirty_delhi/wall.png',
  bg_d1_floor: 'assets/stages/dirty_delhi/floor.png',
  prop_crate: 'assets/props/crate.png',
  prop_crate_b: 'assets/props/crate_b.png',
  prop_matka: 'assets/props/matka.png',
  prop_matka_b: 'assets/props/matka_b.png',
  prop_tyres: 'assets/props/tyres.png',
  prop_tyres_b: 'assets/props/tyres_b.png',
  prop_table: 'assets/props/table.png',
  prop_table_b: 'assets/props/table_b.png',
  prop_sign: 'assets/props/sign.png',
  prop_sign_b: 'assets/props/sign_b.png',
  prop_cart: 'assets/props/cart.png',
  prop_cart_b: 'assets/props/cart_b.png',
  prop_bag: 'assets/props/bag.png',
};

export const ASSETS = Object.fromEntries(Object.keys(FILES).map((k) => [k, null]));

// Everything is authored at RS device pixels per logical px.
const LOGICAL_SCALE = new Set();

export function loadAssets() {
  return Promise.all(Object.entries(FILES).map(([key, src]) => new Promise((resolve) => {
    const img = new Image();
    img.onload = () => { img._as = LOGICAL_SCALE.has(key) ? 1 : RS; ASSETS[key] = img; resolve(); };
    img.onerror = () => { ASSETS[key] = null; resolve(); };
    img.src = src;
  })));
}
