import { INDIA_FILES } from './india_assets.js';
// assets.js - loads game-ready PNGs at boot; each degrades to null if missing.
// NOTE: assets/sources/* are reference-only and are never loaded here.
import { RS } from './engine.js';

export const FILES = {
  ...INDIA_FILES,
  nr_vista_rural: 'assets/stages/night_train/rebuild/vista_rural.png',
  nr_vista_industry: 'assets/stages/night_train/rebuild/vista_industry.png',
  nr_vista_river: 'assets/stages/night_train/rebuild/vista_river.png',
  nr_chad_roof_climb: 'assets/stages/night_train/rebuild/chad_roof_climb.png',
  nr_roof_fittings: 'assets/stages/night_train/rebuild/roof_fittings.png',
  nr_seth_recovery: 'assets/stages/night_train/rebuild/seth_recovery.png',
  nr_seth_roof_climb: 'assets/stages/night_train/rebuild/seth_roof_climb.png',
  nr_seth_intro: 'assets/stages/night_train/rebuild/seth_intro.png',
  nr_office_chair: 'assets/stages/night_train/rebuild/office_chair.png',
  nr_office_desk: 'assets/stages/night_train/rebuild/office_desk.png',
  nr_conductor_intro: 'assets/stages/night_train/rebuild/conductor_intro.png',
  nr_office: 'assets/stages/night_train/rebuild/office.png',
  nr_station_life: 'assets/stages/night_train/rebuild/station_life.png',
  nr_finale_approach_sky: 'assets/stages/night_train/rebuild/finale_approach_sky.png',
  nr_finale_approach_station: 'assets/stages/night_train/rebuild/finale_approach_station.png',
  nr_finale_approach_track: 'assets/stages/night_train/rebuild/finale_approach_track.png',
  nr_finale_approach_platform: 'assets/stages/night_train/rebuild/finale_approach_platform.png',
  nr_finale_approach_clouds: 'assets/stages/night_train/rebuild/finale_approach_clouds.png',
  nr_finale_sky: 'assets/stages/night_train/rebuild/finale_sky.png',
  nr_finale_station: 'assets/stages/night_train/rebuild/finale_station.png',
  nr_finale_track: 'assets/stages/night_train/rebuild/finale_track.png',
  nr_finale_platform: 'assets/stages/night_train/rebuild/finale_platform.png',
  nr_finale_passenger_damage: 'assets/stages/night_train/rebuild/finale_passenger_damage.png',
  nr_finale_cigar: 'assets/stages/night_train/rebuild/finale_cigar.png',
  nr_finale_dynamite: 'assets/stages/night_train/rebuild/finale_dynamite.png',
  nr_finale_smoke: 'assets/stages/night_train/rebuild/finale_smoke.png',
  nr_finale_car: 'assets/stages/night_train/rebuild/finale_car.png',
  nr_finale_charge: 'assets/stages/night_train/rebuild/finale_charge.png',
  nr_finale_bogie: 'assets/stages/night_train/rebuild/finale_bogie.png',
  nr_finale_coupling: 'assets/stages/night_train/rebuild/finale_coupling.png',
  nr_finale_roll: 'assets/stages/night_train/rebuild/finale_roll.png',
  nr_gangway: 'assets/stages/night_train/rebuild/gangway.png',
  nr_roof_escape: 'assets/stages/night_train/rebuild/roof_escape.png',
  nr_wreck: 'assets/stages/night_train/rebuild/wreck.png',
  nr_journey_vista: 'assets/stages/night_train/rebuild/journey_vista.png',
  arcade_defeats: 'assets/fx/arcade_defeats.png',
  boxing_impacts: 'assets/fx/boxing_impacts.png',
  nr_passenger_reaction: 'assets/stages/night_train/rebuild/passenger_reaction.png',
  nr_passenger_seated: 'assets/stages/night_train/rebuild/passenger_seated.png',
  nr_station_tea: 'assets/stages/night_train/rebuild/station_tea.png',

  nr_platform_front: 'assets/stages/night_train/rebuild/platform_front.png',
  nr_join_yard_hall: 'assets/stages/night_train/rebuild/join_yard_hall.png',
  nr_join_hall_platform: 'assets/stages/night_train/rebuild/join_hall_platform.png',
  nr_vestibule: 'assets/stages/night_train/rebuild/vestibule.png',
  nr_chad_board: 'assets/stages/night_train/rebuild/chad_board.png',
  nr_locomotive: 'assets/stages/night_train/rebuild/locomotive.png',
  nr_floor_general_sleeper: 'assets/stages/night_train/rebuild/floor_general_sleeper.png',
  nr_floor_sleeper_pantry: 'assets/stages/night_train/rebuild/floor_sleeper_pantry.png',
  nr_floor_pantry_ac: 'assets/stages/night_train/rebuild/floor_pantry_ac.png',
  nr_floor_ac_private: 'assets/stages/night_train/rebuild/floor_ac_private.png',

  nr_private_damaged:'assets/stages/night_train/rebuild/private_damaged.png',
  nr_rural_near: 'assets/stages/night_train/rebuild/rural_near.png',
  nr_industry_near: 'assets/stages/night_train/rebuild/industry_near.png',
  nr_river_near: 'assets/stages/night_train/rebuild/river_near.png',

  nr_yard: 'assets/stages/night_train/rebuild/yard.png',
  nr_hall: 'assets/stages/night_train/rebuild/hall.png',
  nr_platform: 'assets/stages/night_train/rebuild/platform.png',
  nr_general: 'assets/stages/night_train/rebuild/general.png',
  nr_sleeper: 'assets/stages/night_train/rebuild/sleeper.png',
  nr_pantry: 'assets/stages/night_train/rebuild/pantry.png',
  nr_ac: 'assets/stages/night_train/rebuild/ac.png',
  nr_private: 'assets/stages/night_train/rebuild/private.png',
  nr_roof: 'assets/stages/night_train/rebuild/roof.png',
  nr_rural: 'assets/stages/night_train/rebuild/rural.png',
  nr_industry: 'assets/stages/night_train/rebuild/industry.png',
  nr_river: 'assets/stages/night_train/rebuild/river.png',
  nr_hatch_open: 'assets/stages/night_train/rebuild/hatch_open.png',
  nr_ticket_clerk: 'assets/stages/night_train/rebuild/ticket_clerk.png',
  nr_ticket_scanner: 'assets/stages/night_train/rebuild/ticket_scanner.png',
  nr_chad_entry: 'assets/stages/night_train/rebuild/chad_entry.png',
  nr_chad_cinema: 'assets/stages/night_train/rebuild/chad_cinema.png',
  nr_passengers: 'assets/stages/night_train/rebuild/passengers.png',
  nr_train_exterior: 'assets/stages/night_train/rebuild/train_exterior.png',
  nr_explosion: 'assets/stages/night_train/rebuild/explosion.png',
  nr_gate: 'assets/stages/night_train/rebuild/gate.png',
  prop_nr_case: 'assets/stages/night_train/rebuild/prop_nr_case.png',
  prop_nr_case_b: 'assets/stages/night_train/rebuild/prop_nr_case_b.png',
  prop_nr_trolley: 'assets/stages/night_train/rebuild/prop_nr_trolley.png',
  prop_nr_trolley_b: 'assets/stages/night_train/rebuild/prop_nr_trolley_b.png',
  prop_nr_table: 'assets/stages/night_train/rebuild/prop_nr_table.png',
  prop_nr_table_b: 'assets/stages/night_train/rebuild/prop_nr_table_b.png',
  prop_nr_urn: 'assets/stages/night_train/rebuild/prop_nr_urn.png',
  prop_nr_urn_b: 'assets/stages/night_train/rebuild/prop_nr_urn_b.png',
  prop_nr_contraband: 'assets/stages/night_train/rebuild/prop_nr_contraband.png',
  prop_nr_contraband_b: 'assets/stages/night_train/rebuild/prop_nr_contraband_b.png',
  dialogue_frame: 'assets/ui/dialogue_frame.png',
  direction_arrow: 'assets/ui/direction_arrow.png',
  travel_elevator_cabin: 'assets/travel/elevator/elevator_cabin.png',
  travel_elevator_frame: 'assets/travel/elevator/elevator_frame.png',
  title_art: 'assets/ui/title_art.png',
  logo: 'assets/ui/logo.png',
  go_sign: 'assets/ui/go_sign.png',
  portrait_chad: 'assets/ui/portrait_chad.png',
  results_exhale: 'assets/ui/results_exhale.png',
  results_card: 'assets/ui/results_card.png',
  portrait_chad_48: 'assets/ui/portrait_chad_48.png',
  portrait_raja: 'assets/ui/portrait_raja.png',
  portrait_thekedar: 'assets/ui/portrait_thekedar.png',

  bg_lair_wall: 'assets/lair/wall.png',
  bg_lair_floor: 'assets/lair/floor.png',
  lair_worldmap: 'assets/lair/worldmap.png',
  lair_hifi: 'assets/lair/hifi.png',
  lair_map_panel: 'assets/lair/map_panel.png',
  bg_lair_sky_far: 'assets/lair/sky_far.png',
  bg_lair_sky_near: 'assets/lair/sky_near.png',
  lair_bar_stools: 'assets/lair/bar_stools.png',
  lair_bar_bottles_top: 'assets/lair/bar_bottles_top.png',
  lair_bar_bottles_low: 'assets/lair/bar_bottles_low.png',
  lair_bar_drink_0: 'assets/lair/bar_drink_0.png',
  lair_bar_drink_1: 'assets/lair/bar_drink_1.png',
  lair_bar_drink_2: 'assets/lair/bar_drink_2.png',
  lair_bar_drink_3: 'assets/lair/bar_drink_3.png',
  lair_bar_drink_4: 'assets/lair/bar_drink_4.png',
  lair_humidor: 'assets/lair/humidor.png',
  lair_tankscape: 'assets/lair/tankscape.png',
  lair_tank_frame: 'assets/lair/tank_frame.png',
  lair_baitfish_0: 'assets/lair/baitfish_0.png',
  lair_baitfish_1: 'assets/lair/baitfish_1.png',
  lair_baitfish_2: 'assets/lair/baitfish_2.png',
  lair_baitfish_3: 'assets/lair/baitfish_3.png',
  lair_baitfish_b_0: 'assets/lair/baitfish_b_0.png',
  lair_baitfish_b_1: 'assets/lair/baitfish_b_1.png',
  lair_baitfish_b_2: 'assets/lair/baitfish_b_2.png',
  lair_baitfish_b_3: 'assets/lair/baitfish_b_3.png',
  lair_crab_0: 'assets/lair/crab_0.png',
  lair_crab_1: 'assets/lair/crab_1.png',
  lair_crab_2: 'assets/lair/crab_2.png',
  lair_crab_3: 'assets/lair/crab_3.png',
  lair_lounge_rug: 'assets/lair/lounge_rug.png',
  lair_lounge_chair: 'assets/lair/lounge_chair.png',
  lair_overmantel: 'assets/lair/overmantel.png',
  lair_bag_chain: 'assets/lair/bag_chain.png',
  lair_gloves: 'assets/lair/gloves.png',
  // the master suite: one generation per pose, chaining from sitting up to lying down
  lair_bed_0: 'assets/lair/bed_0.png',
  lair_bed_1: 'assets/lair/bed_1.png',
  lair_bed_2: 'assets/lair/bed_2.png',
  lair_bed_3: 'assets/lair/bed_3.png',
  lair_bed_4: 'assets/lair/bed_4.png',
  lair_bed_5: 'assets/lair/bed_5.png',
  lair_bed_6: 'assets/lair/bed_6.png',
  lair_bed_7: 'assets/lair/bed_7.png',
  // four frames: the logs hold still, the flames move
  lair_fender: 'assets/lair/fender.png',
  lair_fire_0: 'assets/lair/fire_0.png',
  lair_fire_1: 'assets/lair/fire_1.png',
  lair_fire_2: 'assets/lair/fire_2.png',
  lair_fire_3: 'assets/lair/fire_3.png',
  lair_bed_rug: 'assets/lair/bed_rug.png',
  lair_bed_wardrobe: 'assets/lair/bed_wardrobe.png',
  lair_bed_nightstand: 'assets/lair/bed_nightstand.png',
  lair_gym_plates: 'assets/lair/gym_plates.png',
  lair_gym_kettles: 'assets/lair/gym_kettles.png',
  lair_gym_curl: 'assets/lair/gym_curl.png',
  lair_gym_bench: 'assets/lair/gym_bench.png',
  lair_lounge_empty: 'assets/lair/lounge_empty.png',
  lair_lounge_smoke_0: 'assets/lair/lounge_smoke_0.png',
  lair_lounge_smoke_1: 'assets/lair/lounge_smoke_1.png',
  lair_lounge_smoke_2: 'assets/lair/lounge_smoke_2.png',
  lair_lounge_smoke_3: 'assets/lair/lounge_smoke_3.png',
  lair_lounge_smoke_4: 'assets/lair/lounge_smoke_4.png',
  lair_lounge_smoke_5: 'assets/lair/lounge_smoke_5.png',
  lair_lounge_smoke_6: 'assets/lair/lounge_smoke_6.png',
  lair_tiger_lie: 'assets/lair/tiger_lie.png',
  lair_tiger_wake: 'assets/lair/tiger_wake.png',
  lair_tiger_sit: 'assets/lair/tiger_sit.png',
  lair_tiger_stretch: 'assets/lair/tiger_stretch.png',
  lair_tiger_snarl: 'assets/lair/tiger_snarl.png',
  lair_tiger_0: 'assets/lair/tiger_0.png',
  lair_tiger_1: 'assets/lair/tiger_1.png',
  lair_tiger_2: 'assets/lair/tiger_2.png',
  lair_tiger_3: 'assets/lair/tiger_3.png',
  lair_tiger_4: 'assets/lair/tiger_4.png',
  lair_tiger_5: 'assets/lair/tiger_5.png',
  lair_shark_0: 'assets/lair/shark_0.png',
  lair_shark_1: 'assets/lair/shark_1.png',
  lair_shark_2: 'assets/lair/shark_2.png',
  lair_shark_3: 'assets/lair/shark_3.png',
  // keyed by boss id, so js/hub.js can look one up straight off BOSSES
  lair_relic_raja: 'assets/lair/relic_raja.png',
  lair_relic_dredger: 'assets/lair/relic_dredger.png',
  lair_relic_vikram: 'assets/stages/night_train/rebuild/relic_vikram.png',
  lair_relic_sir: 'assets/lair/relic_sir.png',

  prop_bike: 'assets/story/motorcycle/bike.png',
  prop_crate: 'assets/props/crate.png',
  prop_crate_b: 'assets/props/crate_b.png',
  prop_matka: 'assets/props/matka.png',
  prop_matka_b: 'assets/props/matka_b.png',
  prop_tyres: 'assets/props/tyres.png',
  prop_tyres_b: 'assets/props/tyres_b.png',
  prop_table: 'assets/props/table.png',
  prop_table_b: 'assets/props/table_b.png',
  prop_sign: 'assets/props/sign.png',
  prop_sign_b: 'assets/props/sign_b.png',
  prop_cart: 'assets/props/cart.png',
  prop_cart_b: 'assets/props/cart_b.png',
  prop_bag: 'assets/props/bag.png',
  // DIRTY DELHI
  prop_drum: 'assets/props/drum.png',
  prop_drum_b: 'assets/props/drum_b.png',
  prop_mithai: 'assets/props/mithai.png',
  prop_mithai_b: 'assets/props/mithai_b.png',
  prop_thelapole: 'assets/props/thelapole.png',
  prop_thelapole_b: 'assets/props/thelapole_b.png',
  prop_dhobislab: 'assets/props/dhobislab.png',
  prop_dhobislab_b: 'assets/props/dhobislab_b.png',
  prop_winch: 'assets/props/winch.png',
  prop_winch_b: 'assets/props/winch_b.png',
  prop_bucket: 'assets/props/bucket.png',
  prop_bucket_open: 'assets/props/bucket_open.png',
  prop_hose_nozzle: 'assets/props/hose_nozzle.png',
  // THE NIGHT TRAIN

};

export const ASSETS = Object.fromEntries(Object.keys(FILES).map((k) => [k, null]));

// Everything is authored at RS device pixels per logical px.
const LOGICAL_SCALE = new Set();

export function loadAssets() {
  return Promise.all(Object.entries(FILES).map(([key, src]) => new Promise((resolve) => {
    const img = new Image();
    img.onload = () => { img._as = LOGICAL_SCALE.has(key) ? 1 : RS; ASSETS[key] = img; resolve(); };
    img.onerror = () => { ASSETS[key] = null; resolve(); };
    img.src = src;
  })));
}
