// Generated by tools/production/build_delhi_market_vehicles.py; 2× cell pixels.
export const VEHICLE_ART = {
  "cyclist": {
    "cw": 172,
    "ch": 166,
    "half": 42,
    "wheels": {
      "at": [
        [
          36.9,
          131.4,
          27.4
        ],
        [
          135.9,
          131.0,
          28.4
        ]
      ],
      "r": 15.7,
      "n": 18,
      "w": 1,
      "hub": 2.5,
      "col": "rgba(46,33,23,.95)"
    }
  },
  "rickshaw": {
    "cw": 220,
    "ch": 180,
    "half": 53,
    "wheels": {
      "at": [
        [
          38.4,
          144.1,
          29.5
        ],
        [
          183.1,
          144.4,
          29.2
        ]
      ],
      "r": 16.4,
      "n": 12,
      "w": 1.4,
      "hub": 2.5,
      "col": "rgba(46,33,23,.95)",
      "lit": "rgba(176,126,80,.45)"
    }
  }
};
