import { DELHI_SCENERY_FILES } from './delhi_scenery.js';
// Runtime assets for the rebuilt street and office chapters; no alpha-art fallback.
export const INDIA_PANELS = {
 delhi:['market','bazaar','food','vendor','culvert','ghat','wharf','pontoon'],
 refund:['office','annex','calling','calling_east','servers','records','executive','closer'],
};
export const INDIA_PROPS={ic_stall:[64,48],ic_cart:[66,44],ic_boiler:[30,52],ic_cargo:[50,42],ic_monitor:[52,58],ic_cubicle:[72,58],ic_shelf:[56,96],ic_server:[50,104],ic_cabinet:[44,64],ic_execdesk:[98,55],ic_partition:[55,94]};
export const INDIA_FILES={
 ic_rampage_awning:'assets/stages/dirty_delhi/rampage/awning.png',
 ic_chopper:'assets/stages/dirty_delhi/rampage/chopper.png',
 ic_rampage_work:'assets/stages/dirty_delhi/rampage/vendors-working.png',
 ic_rampage_chai:'assets/stages/dirty_delhi/rampage/chai-flee.png',
 ic_rampage_debris:'assets/stages/dirty_delhi/rampage/debris.png',
 ic_intro_fire:'assets/stages/dirty_delhi/rampage/fire.png',
 ic_intro_crowd:'assets/stages/dirty_delhi/rampage/crowd.png',
 ic_rampage_side:'assets/stages/dirty_delhi/rampage/side_stalls.png',ic_rampage_side_wreck:'assets/stages/dirty_delhi/rampage/side_wreck.png',ic_rampage_street:'assets/stages/dirty_delhi/rampage/street_vendors.png',
 ic_rampage_stalls:'assets/stages/dirty_delhi/rampage/stalls.png',ic_rampage_stall_front:'assets/stages/dirty_delhi/rampage/stall_front.png',ic_rampage_stall_burn:'assets/stages/dirty_delhi/rampage/stall_burn.png',ic_ghee_vendor:'assets/stages/dirty_delhi/rampage/ghee_vendor.png',ic_ghee_hit:'assets/stages/dirty_delhi/rampage/ghee_hit.png',ic_ghee_cook:'assets/stages/dirty_delhi/rampage/ghee_cook.png',
 ic_pigeon:'assets/stages/dirty_delhi/rampage/pigeons.png',
 ic_market_set:'assets/stages/india/cinematics/market_set.png',
 ic_kitchen_set:'assets/stages/india/cinematics/kitchen_set.png',
 ic_dredger_set:'assets/stages/india/cinematics/dredger_set.png',
 ic_success_set:'assets/stages/refund_tower/overhaul/success-set.png',
 ic_cine_chad:'assets/stages/india/cinematics/chad_finishers.png',
 ic_cine_push:'assets/stages/india/cinematics/chad_cart_push.png',
 ic_cine_closer:'assets/stages/refund_tower/overhaul/closer_cascade.png',
 ic_cine_splash:'assets/stages/india/cinematics/river_splash.png',
 ic_projectiles:'assets/stages/india/projectiles.png',ic_refund_equipment:'assets/stages/refund_tower/overhaul/equipment.png',ic_vendor_props:'assets/stages/dirty_delhi/finishers/vendor_props.png',ic_vendor_pot:'assets/stages/dirty_delhi/finishers/vendor_pot.png',
 dv_refuge_block:'assets/stages/dirty_delhi/vendor/refuge_block.png',dv_floor_wave:'assets/stages/dirty_delhi/vendor/floor_wave.png',dv_inferno_pillar:'assets/stages/dirty_delhi/vendor/inferno_pillar.png',dv_inferno_wall:'assets/stages/dirty_delhi/vendor/inferno_wall.png',dv_inferno_nova:'assets/stages/dirty_delhi/vendor/inferno_nova.png',
 dv_puri_props:'assets/stages/dirty_delhi/vendor/puri_props.png',dv_puri_pop:'assets/stages/dirty_delhi/vendor/puri_pop.png',
 dv_burner_wreck:'assets/stages/dirty_delhi/vendor/burner_wreck.png',dv_cauldron_shards:'assets/stages/dirty_delhi/vendor/cauldron_shards.png',dv_shattered_cauldron:'assets/stages/dirty_delhi/vendor/shattered_cauldron.png',dv_empty_cauldron:'assets/stages/dirty_delhi/vendor/empty_cauldron.png',dv_kadai:'assets/stages/dirty_delhi/vendor/kadai.png',dv_items:'assets/stages/dirty_delhi/vendor/items.png',dv_breath:'assets/stages/dirty_delhi/vendor/breath.png',dv_inferno_breath:'assets/stages/dirty_delhi/vendor/inferno_breath.png',dv_glob:'assets/stages/dirty_delhi/vendor/glob.png',dv_oil_bomb:'assets/stages/dirty_delhi/vendor/oil_bomb.png',dv_splash:'assets/stages/dirty_delhi/vendor/splash.png',dv_crater:'assets/stages/dirty_delhi/vendor/crater.png',dv_steam:'assets/stages/dirty_delhi/vendor/kitchen_steam.png',dv_flame:'assets/stages/dirty_delhi/vendor/kitchen_flame.png',dv_burner:'assets/stages/dirty_delhi/vendor/kitchen_burner.png',dv_puri:'assets/stages/dirty_delhi/vendor/kitchen_puri.png',dv_oil:'assets/stages/dirty_delhi/vendor/kitchen_oil.png',dv_hang:'assets/stages/dirty_delhi/rebuild/vendor_hanging.png',dv_tawa_patch:'assets/stages/dirty_delhi/vendor/tawa_patch.png',dv_skimmer:'assets/stages/dirty_delhi/vendor/skimmer.png',dv_skimmer_long:'assets/stages/dirty_delhi/vendor/skimmer_long.png',dv_skimmer_floor:'assets/stages/dirty_delhi/vendor/floor_skimmer.png',
 ic_steam:'assets/stages/india/props/steam.png',
 ic_wall_cracked:'assets/stages/refund_tower/overhaul/wall_cracked.png',
 // Approved ivory/plum Scam King: sparse furniture and quiet marble penthouse.
 ...Object.fromEntries(['throne','desk','desk_empty','desk_broken','sideboard','king_throw','handset','handset_v','shades','sleeve','button','bundle','note','giftcard','wall_set'].map(n=>['cl_'+n,`assets/stages/refund_tower/scam_king/${n}.png`])),
 ...DELHI_SCENERY_FILES,
 ...Object.fromEntries(Object.entries(INDIA_PANELS).flatMap(([id,panels])=>panels.map(name=>[`ic_${id}_${name}`,`assets/stages/${id==='delhi'?'dirty_delhi/rebuild':'refund_tower/overhaul'}/${name}.png`]))),
 ic_refund_closer:'assets/stages/refund_tower/scam_king/room.png',
 ...Object.fromEntries(Object.keys(INDIA_PROPS).flatMap(name=>[['prop_'+name,`assets/stages/india/props/${name}.png`],['prop_'+name+'_b',`assets/stages/india/props/${name}_b.png`]])),
 ...Object.fromEntries(['ic_monitor','ic_cubicle','ic_shelf','ic_server','ic_cabinet','ic_execdesk','ic_partition'].flatMap(name=>[['prop_'+name,`assets/stages/refund_tower/overhaul/props/${name}.png`],['prop_'+name+'_b',`assets/stages/refund_tower/overhaul/props/${name}_b.png`]])),

 ic_rat:'assets/stages/dirty_delhi/rebuild/rats.png',ic_street_life:'assets/stages/dirty_delhi/rebuild/street_life.png',  // unused since delhi_life_market.js; kept until the tracked PNG is retired
 ic_office_life:'assets/stages/refund_tower/overhaul/office_life.png',
 ic_office_life_high:'assets/stages/refund_tower/overhaul/office_life_high.png',
 ic_office_life_medium:'assets/stages/refund_tower/overhaul/office_life_medium.png',
 ic_office_life_low:'assets/stages/refund_tower/overhaul/office_life_low.png',
 ic_refund_breach:'assets/stages/refund_tower/overhaul/chad-breach.png',
 ic_office_panic_turn:'assets/stages/refund_tower/overhaul/office-panic-turn.png',
 ic_office_escape_caller:'assets/stages/refund_tower/overhaul/caller-escape.png',
 ic_office_escape_operator:'assets/stages/refund_tower/overhaul/operator-escape.png',
 ic_office_escape_technician:'assets/stages/refund_tower/overhaul/technician-escape.png',
 ic_office_escape_caller_body:'assets/stages/refund_tower/overhaul/caller-escape-body.png',
 ic_office_escape_caller_support:'assets/stages/refund_tower/overhaul/caller-escape-support.png',
 ic_office_escape_operator_body:'assets/stages/refund_tower/overhaul/operator-escape-body.png',
 ic_office_escape_operator_support:'assets/stages/refund_tower/overhaul/operator-escape-support.png',
 ic_office_escape_technician_body:'assets/stages/refund_tower/overhaul/technician-escape-body.png',
 ic_office_escape_technician_support:'assets/stages/refund_tower/overhaul/technician-escape-support.png',
 ic_office_flee_caller:'assets/stages/refund_tower/overhaul/caller-flee.png',
 ic_office_flee_operator:'assets/stages/refund_tower/overhaul/operator-flee.png',
 ic_office_flee_technician:'assets/stages/refund_tower/overhaul/technician-flee.png',
 ic_refund_entrance_debris:'assets/stages/refund_tower/overhaul/entrance-debris.png',
 ic_refund_entrance_desk:'assets/stages/refund_tower/overhaul/entrance-desk-after.png',
 ic_callback_victim:'assets/stages/refund_tower/overhaul/callback-victim.png',
 ic_callback_chad:'assets/stages/refund_tower/overhaul/callback-chad.png',
 ic_callback_props:'assets/stages/refund_tower/overhaul/callback-props.png',
 ic_callback_desk:'assets/stages/refund_tower/overhaul/callback-desk.png',
 ic_callback_cord:'assets/stages/refund_tower/overhaul/callback-cord.png',
 ic_office_stand:'assets/stages/refund_tower/overhaul/office_stand.png',ic_office_turn:'assets/stages/refund_tower/overhaul/office_turn.png',ic_office_chair:'assets/stages/refund_tower/overhaul/props/office_chair.png',
 ic_wall:'assets/stages/refund_tower/overhaul/wall.png',ic_wall_b:'assets/stages/refund_tower/overhaul/wall_b.png',
};
