// GENERATED by tools/production/build_lair_lion.py - do not edit by hand.
// Logical px, from the canvas's bottom centre, art facing right. edge['a>b']: how far
// the lion's x moves forward when pose a becomes b (b>a is the negative).
export const LION_RIG = {
 "poses": [
  "bow_a",
  "bow_a2",
  "bow_b",
  "bow_c",
  "lie",
  "lie_lift",
  "r0",
  "r1",
  "r2",
  "r3",
  "r4",
  "r5",
  "r6",
  "r7",
  "r_land",
  "r_land2",
  "r_land3",
  "rise1",
  "rise1b",
  "rise2",
  "sit",
  "sit_front",
  "sit_turn",
  "sit_up",
  "stand",
  "stand_sit",
  "stretch",
  "stretch_in",
  "stretch_lift",
  "stretch_out",
  "stretch_up",
  "turn",
  "turn_front",
  "w0",
  "w1",
  "w2",
  "w3",
  "w4",
  "w5",
  "w6",
  "w7",
  "wake"
 ],
 "pivot": {
  "turn": 0.1,
  "sit_turn": -0.1,
  "turn_front": -0.1,
  "sit_front": 0.2
 },
 "edge": {
  "wake>rise1": 8.5,
  "rise1>rise1b": 1.0,
  "rise1b>rise2": 4.5,
  "rise2>sit": 4.0,
  "wake>stretch_lift": -0.5,
  "stretch_lift>stretch_in": -2.5,
  "stretch_in>bow_a": -4.5,
  "bow_a>bow_a2": 0.0,
  "bow_a2>stretch": 6.5,
  "stretch>bow_c": 9.0,
  "bow_c>bow_b": 4.5,
  "bow_b>stretch_out": -3.5,
  "stretch_out>stretch_up": -1.0,
  "stretch_up>stand": 1.0,
  "sit>sit_up": -3.5,
  "sit_up>stand": 2.5,
  "stand>stand_sit": -2.0,
  "stand_sit>sit": 1.0,
  "r3>r_land": -5.0,
  "r_land>r_land2": -6.5,
  "r_land2>r_land3": 0.5,
  "r_land3>stand": -3.5,
  "turn>turn_front": 2.5,
  "sit_turn>sit_front": 0.0,
  "stand>w0": 9.0,
  "stand>w1": 9.0,
  "stand>w2": 8.5,
  "stand>w3": 9.0,
  "stand>w4": 10.0,
  "stand>w5": 10.0,
  "stand>w6": 9.0,
  "stand>w7": 9.0,
  "stand>r0": 4.5,
  "stand>r1": 6.0,
  "stand>r2": 8.5,
  "stand>r3": 9.0,
  "stand>r4": 8.5,
  "stand>r5": 9.0,
  "stand>r6": 8.0,
  "stand>r7": 7.5
 },
 "walk": {
  "stride": [
   4.38,
   8.0,
   5.25,
   5.75,
   4.0,
   8.38,
   6.5,
   8.25
  ],
  "stop": [
   4,
   5
  ]
 },
 "run": {
  "stride": [
   8.5,
   24.0,
   -0.25,
   22.5,
   7.5,
   4.75,
   8.5,
   9.5
  ],
  "stop": [
   3
  ],
  "start": [
   1,
   2,
   3,
   4,
   5,
   7
  ]
 },
 "shadow": {
  "lie": [
   -2.7,
   33.8
  ],
  "lie_lift": [
   -2.9,
   32.2
  ],
  "wake": [
   -4.0,
   30.2
  ],
  "stretch_lift": [
   -4.9,
   33.5
  ],
  "stretch_in": [
   -2.6,
   35.2
  ],
  "stretch": [
   3.8,
   31.8
  ],
  "stretch_out": [
   -1.4,
   33.5
  ],
  "stretch_up": [
   -6.8,
   31.5
  ],
  "sit": [
   -3.8,
   21.2
  ],
  "sit_turn": [
   -3.1,
   19.8
  ],
  "sit_up": [
   -5.9,
   26.5
  ],
  "stand": [
   -8.1,
   29.2
  ],
  "turn": [
   -4.4,
   27.8
  ],
  "stand_sit": [
   -6.0,
   24.8
  ],
  "w0": [
   -18.8,
   32.0
  ],
  "w1": [
   -18.7,
   32.0
  ],
  "w2": [
   -18.4,
   32.5
  ],
  "w3": [
   -18.8,
   32.4
  ],
  "w4": [
   -18.5,
   32.1
  ],
  "w5": [
   -18.6,
   32.1
  ],
  "w6": [
   -18.1,
   32.1
  ],
  "w7": [
   -18.5,
   32.1
  ],
  "r0": [
   -13.6,
   36.0
  ],
  "r1": [
   -13.0,
   34.7
  ],
  "r2": [
   -13.8,
   34.5
  ],
  "r3": [
   -14.0,
   33.6
  ],
  "r4": [
   -14.7,
   34.9
  ],
  "r5": [
   -14.6,
   35.5
  ],
  "r6": [
   -14.7,
   35.7
  ],
  "r7": [
   -14.1,
   34.7
  ],
  "rise1": [
   -5.3,
   36.5
  ],
  "rise1b": [
   -5.7,
   32.2
  ],
  "rise2": [
   -4.4,
   27.2
  ],
  "bow_a": [
   3.2,
   36.3
  ],
  "bow_a2": [
   3.2,
   38.5
  ],
  "bow_b": [
   0.8,
   39.2
  ],
  "bow_c": [
   4.2,
   39.0
  ],
  "r_land": [
   -3.5,
   36.0
  ],
  "r_land2": [
   -6.8,
   34.5
  ],
  "r_land3": [
   -6.8,
   34.8
  ],
  "turn_front": [
   0.6,
   14.8
  ],
  "sit_front": [
   -0.1,
   18.8
  ]
 }
};
