// Generated by build_seth_retreat.py. Logical canvas-space pelvis anchors.
export const SETH_RETREAT_FLOOR=132;
export const SETH_RETREAT_ANCHORS=[{"hipY": 93.373}, {"hipY": 92.873}, {"hipY": 100.754}, {"hipY": 102.239}, {"hipY": 109.893}, {"hipY": 115.195}, {"hipY": 112.076}, {"hipY": 110.453}, {"hipY": 102.364}, {"hipY": 104.8}, {"hipY": 102.364}, {"hipY": 99.805}, {"hipY": 106.946}, {"hipY": 85.853}, {"hipY": 82.234}, {"hipY": 86.353}];
export const SETH_CLIMB_HANDS=[100.475, 100.163, 100.163, 108.271];
