const human=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export async function mountActors(host,game,onPlay){
 const [manifest,sprites,assetModule,anchorModule]=await Promise.all([fetch('assets/frames/manifest.json').then(r=>r.json()),game.importModule('js/sprites.js'),game.importModule('js/assets.js'),game.importModule('js/india_cinematic_anchors.js')]);
 const paths={market_work:'ic_rampage_work',chai_flee:'ic_rampage_chai',chad_finishers:'ic_cine_chad',chad_cart_push:'ic_cine_push',closer_cascade:'ic_cine_closer'};
 const anchors={...anchorModule.CINEMATIC_ANCHORS};for(const[k,n]of Object.entries({pressure_vendor:12,market_work:16,chai_flee:8}))anchors[k]={rows:n/4,hip:Array(n)};
 host.innerHTML='<input id="actor-search" type="search" placeholder="Find character…"><label>Character <select id="character"></select></label><input id="animation-search" type="search" placeholder="Find animation…"><label>Animation <select id="action"></select></label><label>Facing <select id="facing"><option value="1">Right</option><option value="-1">Left</option></select></label><label>Ticks / pose <input id="hold" type="number" value="8" min="1" max="60"></label><label>Background <select id="actor-background"><option value="dark">Dark</option><option value="light">Light</option><option value="checker">Checkerboard</option></select></label><label>Guides <input type="checkbox" id="actor-guides" checked></label><label>Loop <input type="checkbox" id="actor-loop" checked></label><button id="pose-play">Play animation</button><button id="pose-back">Previous pose</button><button id="pose-step">Next pose</button><input id="pose-index" aria-label="Animation pose" type="range" min="0" value="0"><div id="pose-status" class="muted"></div><canvas id="pose-live" class="actor-preview" width="240" height="160"></canvas><p class="muted">Gameplay reference / selected pose</p><canvas id="pose-compare" class="actor-preview" width="240" height="160"></canvas><canvas id="poses" class="actor-sheet" width="480" height="160"></canvas>';
 const $=id=>host.querySelector('#'+id),keys=[...Object.keys(manifest),...Object.keys(paths).filter(k=>anchors[k]).map(k=>'cine:'+k)];let pose=0,playing=false,disposed=false;
 function fillCharacters(){const prior=$('character').value;$('character').replaceChildren(...keys.filter(k=>human(k).toLowerCase().includes($('actor-search').value.toLowerCase())).map(k=>new Option(human(k.replace('cine:','Cinematic · ')),k)));if([...$('character').options].some(o=>o.value===prior))$('character').value=prior;fillActions();}
 function fillActions(){const key=$('character').value,prior=$('action').value,states=key.startsWith('cine:')?['performance']:Object.keys(manifest[key]||{});$('action').replaceChildren(...states.filter(k=>human(k).toLowerCase().includes($('animation-search').value.toLowerCase())).map(k=>new Option(human(k),k)));if([...$('action').options].some(o=>o.value===prior))$('action').value=prior;stop();pose=0;draw();}
 function count(){const k=$('character').value;return k.startsWith('cine:')?anchors[k.slice(5)]?.hip.length||0:manifest[k]?.[$('action').value]?.length||0;}
 function background(ctx){const mode=$('actor-background').value;ctx.fillStyle=mode==='light'?'#eee9dd':'#202730';ctx.fillRect(0,0,ctx.canvas.width,ctx.canvas.height);if(mode==='checker'){for(let y=0;y<ctx.canvas.height;y+=12)for(let x=0;x<ctx.canvas.width;x+=12)if((x/12+y/12)%2){ctx.fillStyle='#69727b';ctx.fillRect(x,y,12,12);}}ctx.imageSmoothingEnabled=false;}
 function renderPose(ctx,i,x,ground,reference=false){let k=$('character').value;const {getFrame,SPR,frameW,frameH,blit}=sprites;if(k.startsWith('cine:')&&!reference){k=k.slice(5);const im=assetModule.ASSETS[paths[k]],meta=anchors[k];if(!im)return;ctx.save();ctx.translate(x,ground);ctx.scale(+$('facing').value,1);const sw=im.width/4,sh=im.height/meta.rows;ctx.drawImage(im,i%4*sw,Math.floor(i/4)*sh,sw,sh,-64,-124,128,128);ctx.restore();return;}
 if(k.startsWith('cine:'))k=({closer_cascade:'ic_closer_damaged'})[k.slice(5)]||'player';const f=getFrame(SPR[k],reference?'idle':$('action').value,reference?0:i,+$('facing').value);if(f)blit(ctx,f,x-frameW(f)/2,ground-frameH(f)+4);}
 function guides(ctx,x,w){if(!$('actor-guides').checked)return;for(const y of[38,65,88,130]){ctx.strokeStyle=y===130?'#d4ac69':'#74818b80';ctx.beginPath();ctx.moveTo(x,y+.5);ctx.lineTo(x+w,y+.5);ctx.stroke();}}
 function draw(){const n=count();pose=Math.max(0,Math.min(pose,n-1));$('pose-index').max=Math.max(0,n-1);$('pose-index').value=pose;$('pose-status').textContent=n?`${n} poses · selected ${pose}`:'No matching animation';const live=$('pose-live').getContext('2d');background(live);guides(live,0,240);if(n)renderPose(live,pose,120,130);const comparison=$('pose-compare').getContext('2d');background(comparison);guides(comparison,0,240);if(n){renderPose(comparison,0,60,130,true);renderPose(comparison,pose,180,130);}const c=$('poses');c.height=Math.max(160,Math.ceil(n/4)*160);const ctx=c.getContext('2d');background(ctx);for(let i=0;i<n;i++){ctx.save();ctx.translate(i%4*120,Math.floor(i/4)*160);guides(ctx,0,120);renderPose(ctx,i,60,130);ctx.fillStyle='#d7a759';ctx.font='10px system-ui';ctx.fillText(i,5,152);if(i===pose){ctx.strokeStyle='#f1c57e';ctx.strokeRect(.5,.5,119,159);}ctx.restore();}}
 function stop(){playing=false;$('pose-play').textContent='Play animation';}
 $('actor-search').oninput=fillCharacters;$('character').onchange=()=>{$('animation-search').value='';fillActions();};$('animation-search').oninput=fillActions;$('action').onchange=()=>{stop();pose=0;draw();};for(const id of['facing','actor-background','actor-guides'])$(id).onchange=draw;
 $('pose-play').onclick=()=>{playing=!playing;if(playing)onPlay();$('pose-play').textContent=playing?'Pause animation':'Play animation';};$('pose-step').onclick=()=>{stop();pose=(pose+1)%Math.max(1,count());draw();};$('pose-back').onclick=()=>{stop();pose=(pose-1+count())%Math.max(1,count());draw();};$('pose-index').oninput=()=>{stop();pose=+$('pose-index').value;draw();};$('poses').onclick=e=>{const c=$('poses'),r=c.getBoundingClientRect();stop();pose=Math.floor((e.clientX-r.left)*c.width/r.width/120)+4*Math.floor((e.clientY-r.top)*c.height/r.height/160);draw();};
 let last=0,acc=0;function loop(t){if(disposed)return;if(playing){acc+=Math.min(100,t-last);const step=Math.max(1,+$('hold').value)*1000/60;while(acc>=step){acc-=step;if(pose+1>=count()&&!$('actor-loop').checked){stop();break;}pose=(pose+1)%Math.max(1,count());}draw();}else acc=0;last=t;requestAnimationFrame(loop);}requestAnimationFrame(loop);fillCharacters();$('character').value='player';fillActions();return{stop,dispose(){disposed=true;stop();},select(key,action){$('actor-search').value='';fillCharacters();$('character').value=key;fillActions();if(action){$('action').value=action;draw();}}};
}
