import {VENDOR_WALK_CELLS} from '../../js/vendor_walk_motion.js';
// Specialist Review Studio modules. These never initialize input or touch campaign saves.
const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
function select(host,label,items){const wrap=el('label',label,'studio-field'),s=el('select');s.setAttribute('aria-label',label);for(const [value,name]of items){const o=el('option',name);o.value=value;s.append(o);}wrap.append(s);host.append(wrap);return s;}
function button(host,label,fn){const b=el('button',label,'studio-button');b.type='button';b.onclick=fn;host.append(b);return b;}
function check(host,label,value=true){const l=el('label',label,'studio-check'),i=el('input');i.type='checkbox';i.checked=value;l.prepend(i);host.append(l);return i;}
const json=async(path,fallback)=>{try{const r=await fetch(path);if(!r.ok)throw Error(r.status);return await r.json();}catch{return fallback;}};
const loadImage=async(path)=>{try{const im=new Image();im.src=path;await im.decode();return im;}catch{return null;}};
function workspace(host){
 host.replaceChildren();const bar=el('div','','studio-toolbar'),canvas=el('canvas','','studio-specialist-canvas'),status=el('p','','studio-status');
 canvas.width=960;canvas.height=540;canvas.style.cssText='display:block;width:960px;height:540px;max-width:none;flex-shrink:0;image-rendering:pixelated';
 const viewport=el('div','','studio-specialist-viewport');viewport.style.cssText='width:100%;min-width:0;overflow-x:auto';viewport.append(canvas);host.append(bar,viewport,status);
 const size=select(bar,'Display',[['2','2× · 960 × 540'],['1','Native · 480 × 270']]);let preferred=2;
 function fit(){const actual=preferred===2&&viewport.clientWidth>=960?2:1;canvas.style.width=actual*480+'px';canvas.style.height=actual*270+'px';size.value=String(actual);}
 size.onchange=()=>{preferred=Number(size.value);fit();};const observer=new ResizeObserver(fit);observer.observe(viewport);fit();
 return{bar,canvas,status,ctx:canvas.getContext('2d'),disposeResize:()=>observer.disconnect()};
}
function clock(bar,render,{length=600}={}){let frame=0,playing=false,last=0,carry=0,id=0,disposed=false;const play=button(bar,'Play animation',()=>{playing=!playing;play.textContent=playing?'Pause animation':'Play animation';last=performance.now();});const field=el('input');field.type='number';field.min='0';field.max=String(length-1);field.value='0';field.setAttribute('aria-label','Animation frame');bar.append(field);const speed=select(bar,'Speed',[['1','1×'],['0.5','½×'],['0.25','¼×']]);const seek=n=>{frame=Math.max(0,Math.min(length-1,Math.floor(Number(n)||0)));field.value=frame;render(frame);};for(const d of [-3,-1,1,3])button(bar,`${d>0?'+':''}${d} frame`,()=>{playing=false;play.textContent='Play animation';seek(frame+d);});field.onchange=()=>{playing=false;play.textContent='Play animation';seek(field.value);};const loop=check(bar,'Loop',true);function tick(now){if(disposed)return;if(playing){carry+=Math.min(100,now-last)*.06*Number(speed.value);const n=Math.floor(carry);carry-=n;if(n){if(frame+n>=length&&!loop.checked){playing=false;play.textContent='Play animation';seek(length-1);}else seek((frame+n)%length);}}last=now;id=requestAnimationFrame(tick);}id=requestAnimationFrame(tick);return{seek,play(){if(disposed)return;playing=true;last=performance.now();play.textContent='Pause animation';},pause(){playing=false;carry=0;play.textContent='Play animation';},snapshot(){return{tick:frame,playing,duration:length};},refresh:()=>render(frame),get frame(){return frame;},dispose(){disposed=true;cancelAnimationFrame(id);}};}
function clockAPI(c){return{capabilities:{timeline:true,capture:true},play:()=>c.play(),pause:()=>c.pause(),seek:n=>{c.pause();c.seek(n);return c.snapshot();},step:n=>{c.pause();c.seek(c.frame+Number(n??1));return c.snapshot();},restart:()=>{c.pause();c.seek(0);return c.snapshot();},snapshot:()=>c.snapshot()};}
function background(ctx,kind){ctx.setTransform(2,0,0,2,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle=kind==='light'?'#eee9df':'#151821';ctx.fillRect(0,0,480,270);if(kind==='checker')for(let y=0;y<270;y+=12)for(let x=0;x<480;x+=12)if((x+y)/12%2===0){ctx.fillStyle='#343946';ctx.fillRect(x,y,12,12);}}
let actorRuntime;
function withVendorMotion(a,s,m){
 let walk;
 return {...a,...s,getAIFrame(key,state){
  if(key!=='ic_vendor'||state!=='demon_walk3')return a.getAIFrame(key,state);
  if(!walk){const f=Array.from({length:VENDOR_WALK_CELLS},(_,i)=>m.vendorWalkMotion(s.SPR.ic_vendor,i,1));if(f.some(v=>!v))return a.getAIFrame(key,state);walk={f,fl:f.map((_,i)=>m.vendorWalkMotion(s.SPR.ic_vendor,i,-1))};}
  return walk;
 }};
}
async function actors(game){
 if(game?.importModule){const [a,s,m]=await Promise.all([game.importModule('js/aiframes.js'),game.importModule('js/sprites.js'),game.importModule('js/vendor_walk_motion.js')]);return withVendorMotion(a,s,m);}
 if(!actorRuntime)actorRuntime=(async()=>{const [a,s,m]=await Promise.all([import('../../js/aiframes.js'),import('../../js/sprites.js'),import('../../js/vendor_walk_motion.js')]);await a.loadAIFrames();return withVendorMotion(a,s,m);})();
 return actorRuntime;
}

async function mountAssets({host,baseURL,kind,game,settings={}}){
 const w=workspace(host),{bar,ctx,status,canvas,disposeResize}=w;status.textContent='Loading asset index…';
 const [{FILES},manifest]=await Promise.all([import('../../js/assets.js'),json(new URL('assets/frames/manifest.json',baseURL),{})]);
 const search=el('input');search.type='search';search.placeholder='Search actor, animation or asset';search.setAttribute('aria-label','Search assets');bar.append(search);
 const mode=select(bar,'Collection',kind==='lair'?[['art','Lair artwork']]:[['actor','Actors · runtime scale'],['lineup','Cast line-up · runtime scale'],['art','Environment, props and effects']]);
 const actor=select(bar,'Actor',Object.keys(manifest).map(k=>[k,k.replaceAll('_',' ')]));
 const CASTS={train:['nr_brawler','nr_chai','nr_paan','nr_tte','nr_rack','nr_commando','nr_captain'],'train-bosses':['nr_conductor','nr_neta_guard','nr_neta'],delhi:['ic_brawler','ic_runner','ic_enforcer','ic_heavy','ic_kitchen','ic_docker'],'delhi-bosses':['ic_vendor','dl_thekedar'],refund:['ic_headset','ic_operator','ic_thrower','ic_security','ic_cabinet','ic_lead'],'refund-bosses':['ic_closer','ic_closer_damaged']};
 const cast=select(bar,'Cast',[['train','Night Train · enemies'],['train-bosses','Night Train · bosses'],['delhi','Dirty Delhi · enemies'],['delhi-bosses','Dirty Delhi · bosses'],['refund','Refund Tower · enemies'],['refund-bosses','Refund Tower · boss']]);const lineupStates=()=>[...new Set(['idle','walk','atk','hurt','down','getup','block','stagger_polish','taunt',...CASTS[cast.value].flatMap(k=>Object.keys(manifest[k]||{}))])];
 const anim=select(bar,'Animation',[]),asset=select(bar,'Asset',[]);
 const face=select(bar,'Facing',[['1','Right'],['-1','Left']]),bg=select(bar,'Background',[['dark','Dark'],['light','Light'],['checker','Checkerboard']]);
 const guides=check(bar,'Ground and centre guides'),box=check(bar,'Canvas bounds',false),compare=check(bar,'Compare gameplay idle',false);
 const anchors=el('div','','studio-toolbar');bar.append(anchors);const holds=select(bar,'Ticks per pose',[['8','8'],['4','4'],['12','12'],['18','18'],['1','1']]);
 let runtime=null,current=null,disposed=false,request=0,offsets={};const download=(value,name)=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};for(const[dx,dy,label]of[[-1,0,'Nudge left'],[1,0,'Nudge right'],[0,-1,'Nudge up'],[0,1,'Nudge down']])button(anchors,label,()=>{const frames=runtime?.getAIFrame(actor.value,anim.value)?.f;if(!frames?.length)return;const im=frames[Math.floor(c.frame/Number(holds.value))%frames.length];const k=im._file;if(!k)return;const old=offsets[k]||{dx:0,dy:0};offsets[k]={dx:old.dx+dx,dy:old.dy+dy};c.refresh();});button(anchors,'Export anchor adjustments',()=>{const all={...runtime?.allAnchors()};for(const[k,v]of Object.entries(offsets)){const old=all[k]||{dx:0,dy:0};all[k]={dx:old.dx+v.dx,dy:old.dy+v.dy};}download(all,'anchors.json');});
 function options(s,items){const old=s.value;s.replaceChildren();for(const[v,n]of items){const o=el('option',n);o.value=v;s.append(o);}if(items.some(([v])=>v===old))s.value=old;}
 const artItems=Object.entries(FILES).filter(([k,p])=>kind!=='lair'||k.includes('lair')||String(p).includes('/lair/'));
 function render(t){background(ctx,bg.value);if(guides.checked){ctx.strokeStyle='#55a78b';ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(0,228.5);ctx.lineTo(480,228.5);ctx.moveTo(240.5,0);ctx.lineTo(240.5,270);ctx.stroke();}
 if(mode.value==='actor'&&runtime){const list=runtime.getAIFrame(actor.value,anim.value),arr=face.value==='1'?list?.f:list?.fl;if(!arr?.length){status.textContent='No loaded frames for this selection.';return;}const index=Math.floor(t/Number(holds.value))%arr.length,im=arr[index],fw=runtime.frameW(im),fh=runtime.frameH(im),x=compare.checked?310:240;const offset=offsets[im._file]||{dx:0,dy:0};ctx.drawImage(im,x-fw/2+offset.dx,228-fh+offset.dy,fw,fh);if(box.checked){ctx.strokeStyle='#f2c97f';ctx.strokeRect(x-fw/2,228-fh,fw,fh);}if(compare.checked){const ref=runtime.getAIFrame(actor.value,actor.value==='ic_vendor'&&anim.value.startsWith('demon_')?'demon_idle3':'idle')?.f?.[0];if(ref){const rw=runtime.frameW(ref),rh=runtime.frameH(ref);ctx.drawImage(ref,120-rw/2,228-rh,rw,rh);}}status.textContent=`${actor.value} · ${anim.value} · pose ${index+1}/${arr.length} · ${im._file||'runtime sprite'} · actual runtime scale`;}
 else if(mode.value==='lineup'&&runtime){const keys=['player',...CASTS[cast.value]],gap=Math.min(62,440/keys.length),x0=240-gap*(keys.length-1)/2;ctx.font='6px monospace';ctx.textAlign='center';const shown=[];keys.forEach((k,i)=>{const state=k==='player'?'idle':anim.value,list=runtime.getAIFrame(k,state)||runtime.getAIFrame(k,'idle'),arr=face.value==='1'?list?.f:list?.fl;if(!arr?.length)return;const im=arr[Math.floor(t/Number(holds.value))%arr.length],fw=runtime.frameW(im),fh=runtime.frameH(im),x=x0+i*gap;ctx.drawImage(im,x-fw/2,228-fh,fw,fh);ctx.fillStyle=runtime.getAIFrame(k,state)?'#d8c9a8':'#7b6f60';ctx.fillText(k.replace(/^(nr|ic)_/,''),x,240+(i%2)*8);shown.push(k);});status.textContent=`${cast.options[cast.selectedIndex].text} · ${anim.value} (grey label = missing, showing idle) · CHAD idle at left for scale · actual runtime scale`;}
 else if(current){const scale=Math.min(1,480/current.width,270/current.height),ww=current.width*scale,hh=current.height*scale;ctx.drawImage(current,(480-ww)/2,(270-hh)/2,ww,hh);status.textContent=`${asset.value} · ${current.width} × ${current.height} source pixels · fitted sheet preview (not gameplay scale)`;}
 }
 const c=clock(bar,render,{length:3600});
 async function refresh(){const id=++request;current=null;const isActor=mode.value==='actor';const isLineup=mode.value==='lineup';for(const control of [actor,anim,face,holds,compare])control.closest('label').hidden=!isActor&&!(isLineup&&control!==actor&&control!==compare);cast.closest('label').hidden=!isLineup;if(isLineup&&!lineupStates().includes(anim.value))options(anim,lineupStates().map(k=>[k,k.replaceAll('_',' ')]));asset.closest('label').hidden=isActor||isLineup;anchors.hidden=!isActor||actor.value==='ic_vendor'&&anim.value==='demon_walk3';status.textContent='Loading selection…';if(isActor||isLineup){runtime=await actors(game);}else if(!isLineup)current=await loadImage(new URL(FILES[asset.value]||'',baseURL));if(disposed||id!==request)return;c.seek(0);if(!isActor&&!isLineup&&!current)status.textContent='Selected image is unavailable.';}
 function filter(){const q=search.value.toLowerCase();options(asset,artItems.filter(([k,p])=>`${k} ${p}`.toLowerCase().includes(q)).map(([k])=>[k,k.replaceAll('_',' ')]));options(actor,Object.keys(manifest).filter(k=>`${k} ${Object.keys(manifest[k]).join(' ')}`.toLowerCase().includes(q)).map(k=>[k,k.replaceAll('_',' ')]));fillAnimations();}
 function fillAnimations(){if(mode.value==='lineup'){options(anim,lineupStates().map(k=>[k,k.replaceAll('_',' ')]));return refresh();}options(anim,Object.entries(manifest[actor.value]||{}).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,`${k.replaceAll('_',' ')} · ${actor.value==='ic_vendor'&&k==='demon_walk3'?VENDOR_WALK_CELLS:v.length} poses`]));refresh();}
 search.oninput=filter;actor.onchange=fillAnimations;anim.onchange=refresh;asset.onchange=refresh;mode.onchange=()=>{if(mode.value==='lineup')options(anim,lineupStates().map(k=>[k,k.replaceAll('_',' ')]));else fillAnimations();refresh();};cast.onchange=()=>{options(anim,lineupStates().map(k=>[k,k.replaceAll('_',' ')]));refresh();};for(const ctrl of[face,bg,guides,box,compare,holds])ctrl.onchange=c.refresh;
 filter();await refresh();async function apply(v={}){if(v.actor&&manifest[v.actor]){actor.value=v.actor;options(anim,Object.entries(manifest[actor.value]).filter(([,a])=>Array.isArray(a)).map(([k,a])=>[k,`${k.replaceAll('_',' ')} · ${actor.value==='ic_vendor'&&k==='demon_walk3'?VENDOR_WALK_CELLS:a.length} poses`]));}if(v.animation&&[...anim.options].some(o=>o.value===v.animation))anim.value=v.animation;for(const[k,n]of[['facing',face],['background',bg],['hold',holds]])if(v[k]!==undefined)n.value=String(v[k]);if(v.collection!==undefined)mode.value=v.collection;if(v.cast!==undefined)cast.value=v.cast;if(mode.value==='lineup'){options(anim,lineupStates().map(k=>[k,k.replaceAll('_',' ')]));if(v.animation)anim.value=v.animation;}if(v.asset!==undefined)asset.value=v.asset;await refresh();}function values(){return{actor:actor.value,animation:anim.value,facing:Number(face.value),background:bg.value,hold:Number(holds.value),collection:mode.value,asset:asset.value,cast:cast.value};}if(Object.keys(settings).length)await apply(settings);return{...clockAPI(c),setSettings:apply,snapshot:()=>({...c.snapshot(),settings:values()}),dispose(){disposed=true;++request;c.dispose();disposeResize();host.replaceChildren();},capture:()=>canvas.toDataURL('image/png')};
}

async function mountAudio({host,baseURL,settings={}}){
 host.replaceChildren();const bar=el('div','','studio-toolbar'),list=el('div','','studio-tool-list'),status=el('p','','studio-status');host.append(bar,status,list);
 const search=el('input');search.type='search';search.placeholder='Search transcript, role or source';search.setAttribute('aria-label','Search sounds');bar.append(search);
 const bank=select(bar,'Collection',[['runtime','Runtime effects'],['duke','Duke recordings'],['source','Streets of Rage source bank']]);const category=select(bar,'Category',[['','All categories']]);const identification=select(bar,'Identification',[['','All sounds'],['confirmed','Confirmed original uses'],['unknown','Needs identification']]);const volume=el('input');volume.type='range';volume.min='0';volume.max='1';volume.step='.05';volume.value='.7';volume.setAttribute('aria-label','Preview volume');bar.append(volume);
 let active=null,disposed=false;const stop=()=>{if(active){active.pause();active.removeAttribute('src');active.load();active=null;}};button(bar,'Stop preview',stop);volume.oninput=()=>{if(active)active.volume=Number(volume.value);};const hidden=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',hidden);
 const [manifest,duke]=await Promise.all([json(new URL('audio/sfx/manifest.json',baseURL),{}),json(new URL('audio/voice/duke/catalog.json',baseURL),{clips:[]})]);if(disposed)return{dispose:stop};
 for(const cat of[...new Set(duke.clips.map(c=>c.category))].sort()){const o=el('option',cat);o.value=cat;category.append(o);}
 const named=k=>manifest.runtimeLabels?.[k]||k.replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
 const identity=c=>c.verifiedByCode?'original use confirmed from game code':c.verifiedByEar?'listening verified':'original use unconfirmed';
 const sourceInfo=id=>{const c=manifest.catalog?.find(c=>c.id===id);return c?`${c.label} · ${identity(c)} · archive ${id}`:`Archive ${id}`;};
 function render(){stop();list.replaceChildren();category.closest('label').hidden=bank.value!=='duke';identification.closest('label').hidden=bank.value!=='source';let rows=[];
 if(bank.value==='duke')rows=duke.clips.filter(c=>!category.value||c.category===category.value).map(c=>({label:c.transcript,path:`audio/voice/duke/${c.file}`,details:`${c.category} · ${Number(c.duration||0).toFixed(2)}s · ${c.sourceFilename} · transcript: ${c.transcriptProvenance||'pack label'} · listening: ${c.listeningVerified?'verified':'unverified'}`,extra:c.suggestedUse||''}));
 else if(bank.value==='source')rows=(manifest.catalog||[]).filter(c=>!identification.value||(identification.value==='confirmed')===!!(c.verifiedByCode||c.verifiedByEar)).map(c=>({label:c.label,path:`${manifest.rawDir||'audio/sources/streets_of_rage_2'}/${c.file}`,details:`${c.seconds}s · ${identity(c)} · archive ${c.id}${c.roles?.length?' · Used for: '+[...new Set(c.roles.map(named))].join(', '):''}${c.layers?.length?' · Layer in: '+[...new Set(c.layers.map(named))].join(', '):''}`,extra:c.verification?.evidence||''}));
 else {
  const runtime=new Map(Object.entries(manifest.map||{}).map(([k,v])=>[k,{label:named(k),path:`audio/sfx/${k}.wav`,details:`${sourceInfo(v)} · cue ${k}`} ]));
  for(const[k,v]of Object.entries({...manifest.composites,...manifest.generated,...manifest.authored}))runtime.set(k,{label:named(k),path:`audio/sfx/${k}.wav`,details:`${v.label||'Designed effect'} · cue ${k}`,extra:v.verification?.evidence||''});
  rows=[...runtime.values()];
 }
 const q=search.value.toLowerCase(),filtered=rows.filter(r=>`${r.label} ${r.details} ${r.extra||''}`.toLowerCase().includes(q));status.textContent=`${filtered.length} / ${rows.length} samples. Click to audition; each preview stops the previous sound.`;
 for(const row of filtered){const b=button(list,'',()=>{stop();active=new Audio(new URL(row.path,baseURL));active.volume=Number(volume.value);active.play().catch(()=>status.textContent=`Unavailable sample: ${row.path}`);status.textContent=`Playing: ${row.label}`;});b.classList.add('studio-tool-item');b.append(el('strong',row.label),el('small',row.details));b.title=row.extra||row.details;}if(!filtered.length)list.append(el('p','No samples match your search.'));}
 function apply(v={}){if(v.collection!==undefined)bank.value=v.collection;if(v.category!==undefined)category.value=v.category;if(v.identification!==undefined)identification.value=v.identification;if(v.search!==undefined)search.value=v.search;if(v.volume!==undefined)volume.value=String(Math.max(0,Math.min(1,Number(v.volume))));render();}search.oninput=render;bank.onchange=render;category.onchange=render;identification.onchange=render;apply(settings);return{setSettings:apply,capabilities:{timeline:false,capture:false},play(){return false;},pause:stop,stop,restart:stop,snapshot:()=>({tick:0,playing:!!active&&!active.paused,settings:{collection:bank.value,category:category.value,identification:identification.value,search:search.value,volume:Number(volume.value)}}),dispose(){disposed=true;stop();document.removeEventListener('visibilitychange',hidden);host.replaceChildren();}};
}

async function mountPresentation({host,baseURL,settings={}}){
 const {bar,canvas,ctx,status,disposeResize}=workspace(host);status.textContent='Loading presentation artwork…';
 const [title,{loadDisplayType}]=await Promise.all([import('../../js/title_motion.js?v=active-presentation-1'),import('../../js/display_type.js')]);await loadDisplayType();
 const art=await title.loadTitleMotion();
 const variant=select(bar,'Performance',title.TITLE_VARIANTS.map(c=>[c.id,c.name]));
 const back=select(bar,'Backdrop',[['','World Tour']]),ui=check(bar,'Lettering and menu'),effects=check(bar,'Smoke and lights'),hero=check(bar,'CHAD');
 const c=clock(bar,t=>{ctx.setTransform(2,0,0,2,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,480,270);const images=hero.checked?art:{...art,[variant.value]:null};const pose=title.drawTitleMotion(ctx,images,variant.value,t,{ui:ui.checked,effects:effects.checked,background:back.value||undefined});status.textContent=`Frame ${Math.floor(t)} · Pose ${pose.frame+1} · ${pose.action}`;},{length:600});
 function refresh(){for(const n of[variant,back])n.closest('label').hidden=true;c.refresh();}
 const params=new URLSearchParams(location.search);const choice=settings.variant||params.get('variant')||params.get('option');if(choice&&[...variant.options].some(o=>o.value===choice))variant.value=choice;function apply(v={}){if(v.variant!==undefined&&[...variant.options].some(o=>o.value===v.variant))variant.value=v.variant;if(v.background!==undefined)back.value=v.background;for(const[k,n]of[['ui',ui],['effects',effects],['hero',hero]])if(v[k]!==undefined)n.checked=!!v[k];refresh();}for(const n of[variant,back,ui,effects,hero])n.onchange=refresh;apply(settings);return{...clockAPI(c),setSettings:apply,snapshot:()=>({...c.snapshot(),settings:{presentation:'title',variant:variant.value,background:back.value,ui:ui.checked,effects:effects.checked,hero:hero.checked}}),dispose(){c.dispose();disposeResize();host.replaceChildren();},capture:()=>canvas.toDataURL('image/png')};
}
export async function mountSpecialist(options){const args={...options,baseURL:options.baseURL||new URL('../../',import.meta.url)};if(args.kind==='audio')return mountAudio(args);if(args.kind==='presentation')return mountPresentation(args);if(args.kind==='lair'&&args.game?.hub)return mountLair(args);if(args.kind==='assets'&&args.game?.importModule)return mountAssetSuite(args);return mountAssets(args);}

async function mountLair({host,baseURL,game}){
 const {bar,canvas,ctx,status,disposeResize}=workspace(host),hub=await game.importModule('js/hub.js');
 const mode=select(bar,'View',[['room','Live room'],['art','Isolated artwork']]);
 const zones=[['290','The lounge'],['640','Trophies and media'],['1100','The view'],['1700','Master suite']];
 const zone=select(bar,'Zone',zones),fixture=select(bar,'Fixture',hub.FIXTURES.map(f=>[f.id,f.hint]));
 const markers=check(bar,'Fixture markers',false);let at=290,lastFrame=0,acted=false;const source=game.window.document.querySelector('canvas');
 function reset(){game.resetInput?.();game.hub();game.G.freezeTime=true;game.G.player.x=at;game.G.player.vx=0;game.G.camX=Math.max(0,Math.min(game.G.camMax,at-240));game.G.fade=0;lastFrame=0;acted=false;}
 function render(t){if(t<lastFrame)reset();game.G.freezeTime=false;for(let i=lastFrame;i<t;i++){if(acted&&i===lastFrame)game.release('use');game.step(1);}game.G.freezeTime=true;lastFrame=t;game.render();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,960,540);ctx.drawImage(source,0,0,960,540);if(markers.checked){ctx.setTransform(2,0,0,2,0,0);ctx.strokeStyle='#e8c677';ctx.font='7px monospace';for(const f of hub.FIXTURES){const x=f.x-game.G.camX;if(x<0||x>480)continue;ctx.beginPath();ctx.moveTo(x,25);ctx.lineTo(x,245);ctx.stroke();ctx.fillStyle='#e8c677';ctx.fillText(f.hint,x+3,42);}}status.textContent=`The Lair · frame ${t} · room updates and draw order from the game runtime`;}
 reset();const c=clock(bar,render,{length:36000});
 const action=button(bar,'Use selected fixture',()=>{const f=hub.FIXTURES.find(f=>f.id===fixture.value);if(!f)return;at=f.x;reset();game.G.freezeTime=false;game.press(f.id==='bag'?'attack':'use');game.step(1);game.release(f.id==='bag'?'attack':'use');game.G.freezeTime=true;acted=true;c.seek(0);});
 zone.onchange=()=>{at=Number(zone.value);reset();c.seek(0);};markers.onchange=c.refresh;
 let artwork=null;const artHost=el('div','','studio-specialist-art');host.append(artHost);
 mode.onchange=async()=>{c.pause();const art=mode.value==='art';canvas.hidden=art;for(const n of[zone,fixture,markers])n.closest('label').hidden=art;action.hidden=art;artHost.hidden=!art;if(art&&!artwork)artwork=await mountAssets({host:artHost,baseURL,kind:'lair',game});};artHost.hidden=true;c.seek(0);
 return{...clockAPI(c),play:()=>mode.value==='art'?artwork?.play():c.play(),pause:()=>{c.pause();artwork?.pause();},seek:n=>mode.value==='art'?artwork?.seek(n):(c.pause(),c.seek(n),c.snapshot()),step:n=>mode.value==='art'?artwork?.step(n):(c.pause(),c.seek(c.frame+Number(n??1)),c.snapshot()),restart:()=>mode.value==='art'?artwork?.restart():(c.pause(),reset(),c.seek(0),c.snapshot()),snapshot:()=>mode.value==='art'?artwork?.snapshot():c.snapshot(),dispose(){c.dispose();disposeResize();artwork?.dispose();game.resetInput?.();game.G.freezeTime=true;host.replaceChildren();},capture:()=>mode.value==='art'?artwork?.capture():canvas.toDataURL('image/png')};
}

async function mountAssetSuite(args){
 const {host}=args;host.replaceChildren();const nav=el('div','','studio-toolbar'),body=el('div');host.append(nav,body);const mode=select(nav,'Workspace',[['assets','Actors and source assets'],['scene','Stages, crowd placement and effects']]);let child=null,serial=0;
 async function mount(){const id=++serial;child?.dispose();child=null;const next=await(mode.value==='assets'?mountAssets({...args,host:body}):mountSceneTools({...args,host:body}));if(id!==serial)next.dispose();else child=next;}
 mode.onchange=mount;await mount();return{get capabilities(){return child?.capabilities||{};},setSettings:v=>child?.setSettings?.(v),play:()=>child?.play?.(),pause:()=>child?.pause?.(),seek:n=>child?.seek?.(n),step:n=>child?.step?.(n),restart:()=>child?.restart?.(),snapshot:()=>child?.snapshot?.()||{tick:0,playing:false},dispose(){++serial;child?.dispose();host.replaceChildren();},capture:()=>child?.capture?.()};
}
async function mountSceneTools({host,game}){
 const {bar,canvas,ctx,status,disposeResize}=workspace(host),[crowd,fx]=await Promise.all([game.importModule('js/crowd.js'),game.importModule('js/effects.js')]);
 const stage=select(bar,'Stage',game.STAGES.map((s,i)=>[String(i),s.name])),actor=select(bar,'Crowd actor',[]),solo=check(bar,'Isolate actor',false),hide=check(bar,'Hide selected actor',false),grid=check(bar,'Ground guides',true);
 const cam=el('input');cam.type='range';cam.min='0';cam.max='1';cam.step='1';cam.value='0';cam.setAttribute('aria-label','Stage camera');bar.append(cam);const source=game.window.document.querySelector('canvas');let lastFrame=0;
 const patch={};function current(){return game.G.crowd?.[Number(actor.value)];}
 function init(){game.stage(Number(stage.value));game.G.freezeTime=true;game.G.enemies=[];game.G.spawnQueue=[];game.G.waveActive=false;game.G.locked=false;game.G.boss=null;game.G.fade=0;lastFrame=0;cam.max=String(game.G.camMax);actor.replaceChildren();for(const[a,i]of(game.G.crowd||[]).map((a,i)=>[a,i])){const o=el('option',`${a.kind} · x ${Math.round(a.x)}`);o.value=i;actor.append(o);}status.textContent=game.G.crowd?.length?'Select a crowd actor to inspect placement. Edits are session-only; export the patch to retain them.':'This stage has no legacy crowd actors. Its authored stage actors remain available through campaign inspection.';}
 function render(t){if(t<lastFrame)init();game.G.freezeTime=false;for(let i=lastFrame;i<t;i++)game.step(1);game.G.freezeTime=true;lastFrame=t;game.G.camX=Number(cam.value);const saved=game.G.crowd,selected=current();if(solo.checked)game.G.crowd=selected?[selected]:[];if(hide.checked)game.G.crowd=(game.G.crowd||[]).filter(a=>a!==selected);game.render();game.G.crowd=saved;ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(source,0,0,960,540);if(grid.checked){ctx.setTransform(2,0,0,2,0,0);ctx.strokeStyle='#71c5a655';for(let y=180;y<260;y+=10){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(480,y);ctx.stroke();}}}
 init();const c=clock(bar,render,{length:36000});stage.onchange=()=>{init();c.seek(0);};cam.oninput=c.refresh;for(const v of[solo,hide,grid])v.onchange=c.refresh;actor.onchange=()=>{const a=current();if(a){cam.value=Math.max(0,Math.min(game.G.camMax,a.x-240));c.refresh();}};
 for(const[dx,dy,ds,label]of[[-1,0,0,'Actor ←'],[1,0,0,'Actor →'],[0,-1,0,'Actor ↑'],[0,1,0,'Actor ↓'],[0,0,-.02,'Smaller'],[0,0,.02,'Larger']])button(bar,label,()=>{const a=current();if(!a)return;a.x+=dx;a.y+=dy;a.scale=Math.max(.2,a.scale+ds);const key=a.key||crowd.crowdKey(a);patch[key]={x:a.x,y:a.y,scale:a.scale};c.refresh();});
 button(bar,'Export crowd placement',()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({...crowd.crowdOverrides(),...patch},null,2)],{type:'application/json'}));a.download='crowd-overrides.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
 const effect=select(bar,'Effect',[['spawnSpark','Hit spark'],['spawnDust','Contact dust'],['spawnShock','Shock'],['spawnRing','Ring'],['spawnSteam','Steam'],['spawnSmoke','Smoke'],['spawnDebris','Debris']]);button(bar,'Trigger effect',()=>{fx[effect.value](game.G.camX+240,220,effect.value==='spawnRing'?'#ffd94a':8);c.refresh();});c.seek(0);
 return{...clockAPI(c),dispose(){c.dispose();disposeResize();game.resetInput?.();game.G.freezeTime=true;host.replaceChildren();},capture:()=>canvas.toDataURL('image/png')};
}
