import {createController} from './controller.js?v=review-controls-3';
import {createScenarioRegistry} from './scenarios.js?v=guard-surrender-1';
import {mountSpecialist} from './specialists.js?v=cast-lineup-4';
import {mountActors} from './actors.js';
const $=id=>document.getElementById(id),baseURL=new URL('../../',import.meta.url),frame=$('game');
const sections=[['trip','Home & Trip'],['train','Night Train'],['delhi','Dirty Delhi'],['refund','Refund Tower'],['assets','Animations & Assets'],['audio','Audio'],['presentation','Presentation']];
const groups={areas:'Areas',fights:'Fights',duels:'Enemy 1v1s',cinematics:'Cinematics',results:'Results'};
let controller,registry=[],actorPanel,specialist=null,current=null,section='train',mode='play',busy=false,loadingChain=Promise.resolve(),navVersion=0,lastReadout=0;
const toolEntries=sections.slice(4).map(([id,label])=>({id:'tools/'+id,section:id,label,group:'tools',kind:'tool',description:({assets:'Browse actors, poses and source art; inspect registration and stage placement.',audio:'Find and audition effects, music and Duke recordings. Source labels remain explicit.',presentation:'Inspect the active title and loading screen with their actual renderers.'})[id],layers:[],checkpoints:[],duration:0}));
toolEntries.push({id:'trip/lair-inspector',section:'trip',group:'areas',label:'Lair · fixtures and artwork',kind:'tool',toolKind:'lair',description:'Inspect home fixtures, actor routines and their registered artwork.',layers:[],checkpoints:[],duration:0});
function error(e){console.error(e);$('status').textContent=e.message||String(e);$('status').classList.add('error');$('loading').hidden=true;}
function notify(text){$('status').classList.remove('error');$('status').textContent=text;}
function isTool(){return current?.kind==='tool';}
function serial(fn){const p=loadingChain.catch(()=>{}).then(fn);loadingChain=p;p.catch(error);return p;}
function prefs(){try{return JSON.parse(localStorage.getItem('review.studio')||'{}');}catch{return{};}}
function remember(){try{localStorage.setItem('review.studio',JSON.stringify({id:current?.id,mode,sound:$('sound').checked}));}catch{}}
function linkURL(){const q=new URLSearchParams();if(current)q.set('scenario',current.id);if(!isTool()&&controller?.snapshot().tick)q.set('t',controller.snapshot().tick);if(mode==='inspect')q.set('mode','inspect');if(isTool()){const tool=specialist?.snapshot?.();if(tool?.tick)q.set('t',tool.tick);if(tool?.settings)q.set('settings',JSON.stringify(tool.settings));}const s=controller?.snapshot();if(s?.seed!==541)q.set('seed',s.seed);if(!isTool()&&s){const values={...s.settings};delete values.seed;if(Object.keys(values.layers||{}).length===0)delete values.layers;if(Object.keys(values).length)q.set('settings',JSON.stringify(values));}return 'review.html?'+q;}
function routeHistory(replace=false){if(current){history[replace?'replaceState':'pushState'](null,'',linkURL());remember();}}
function navigation(){const q=$('search').value.trim().toLowerCase();$('sections').replaceChildren();for(const[id,label]of sections){if(id==='assets'){const title=document.createElement('div');title.className='nav-group-title';title.textContent='Tools';$('sections').append(title);}const b=document.createElement('button');b.textContent=label;b.dataset.section=id;if(section===id)b.setAttribute('aria-current','page');b.onclick=()=>{section=id;$('search').value='';$('group-filter').value='all';navigation();if(toolEntries.some(t=>t.section===id))load('tools/'+id);else{const first=registry.find(s=>s.section===id&&s.kind==='area')||registry.find(s=>s.section===id);if(first)load(first.id);}};$('sections').append(b);}
 const list=$('scenario-list');list.replaceChildren();const matches=registry.filter(s=>q?`${s.label} ${s.section} ${s.description} ${s.id}`.toLowerCase().includes(q):s.section===section).filter(s=>q||$('group-filter').value==='all'||s.group===$('group-filter').value||s.kind==='tool');if(!matches.length){const p=document.createElement('p');p.className='empty';p.textContent='No matching scenarios. Try a character, area or move name.';list.append(p);return;}
 for(const[group,label]of Object.entries({...groups,tools:'Tools'})){const items=matches.filter(s=>s.group===group&&s.kind!=='full');if(!items.length)continue;const title=document.createElement('div');title.className='nav-group-title';title.textContent=label;list.append(title);for(const s of items){const b=document.createElement('button');b.className='scenario';b.dataset.scenario=s.id;b.textContent=s.label;b.setAttribute('aria-current',String(current?.id===s.id));if(q){const sub=document.createElement('small');sub.textContent=sections.find(x=>x[0]===s.section)?.[1]||s.section;b.append(sub);}b.onclick=()=>load(s.id);list.append(b);}}
}
function changeMode(value,write=true){mode=value==='inspect'?'inspect':'play';document.body.classList.toggle('inspect',mode==='inspect');$('mode-play').setAttribute('aria-pressed',String(mode==='play'));$('mode-inspect').setAttribute('aria-pressed',String(mode==='inspect'));controller?.pause();actorPanel?.stop();specialist?.pause?.();if(write)routeHistory(true);fit();}
// The game fills the space it has (no scrolling to reach the controls); captures and checks can pin 1× or 2× through setScale.
function fit(){const wrap=$('viewport-wrap'),fixed=+$('scale').value;let k=fixed;if(!fixed){const top=wrap.getBoundingClientRect().top+scrollY;k=Math.max(1,Math.min(wrap.clientWidth/480,(innerHeight-top-(mode==='inspect'?190:80))/270));}frame.style.width=Math.floor(480*k)+'px';frame.style.height=Math.floor(270*k)+'px';}
function readout(force=false){if(!controller||isTool())return;const now=performance.now();if(!force&&now-lastReadout<80)return;lastReadout=now;const s=controller.snapshot();$('play').textContent=s.playing?'Pause':({fight:'Play fight',pattern:'Play demonstration',cinematic:'Play cinematic',area:'Explore area',full:'Play level',result:'Play results'})[current?.kind]||'Play';$('play').disabled=busy;$('reset').disabled=busy;$('frame-number').value=s.tick;$('time').max=Math.max(current?.duration||1200,s.tick);$('time').value=s.tick;$('elapsed').value=(s.tick/60).toFixed(2)+'s';$('focus-status').textContent=s.playing?(document.activeElement===frame?'Game focused · keyboard and gamepad active':'Playing · click the game to control it'):'Paused · select a beat or press Play';document.body.classList.toggle('game-focused',s.playing&&document.activeElement===frame);$('diagnostics').textContent=JSON.stringify({scenario:s.scenarioId,frame:s.tick,seed:s.seed,state:s.engine.state,stage:s.engine.stage,enemyCount:s.engine.enemies.length,recordedThrough:s.replayFrames},null,2);}
function inspector(){const s=current;$('checkpoint').replaceChildren(new Option('Jump to a beat…',''));for(const c of s.checkpoints||[])$('checkpoint').add(new Option(`${c.label} · ${c.tick}`,c.tick));$('layers').replaceChildren();const settings=controller.snapshot().settings;for(const l of s.layers||[]){const label=document.createElement('label');label.className='layer-row';const check=document.createElement('input');check.type='checkbox';check.checked=settings.layers?.[l.id]!==false;check.dataset.layer=l.id;check.onchange=()=>controller.setSettings({layers:{[l.id]:check.checked}});label.append(check,document.createTextNode(l.label));$('layers').append(label);}if(!s.layers?.length)$('layers').textContent='No separate layers for this view.';
 const host=$('scenario-controls');host.replaceChildren();for(const c of s.controls||[]){if(c.type==='action')continue;const label=document.createElement('label');label.textContent=c.label;const input=document.createElement(c.type==='select'?'select':'input');input.dataset.setting=c.id;if(c.type==='select'){for(const o of c.options||[])input.add(new Option(o.label,o.value));}else{input.type=c.type||'range';for(const a of['min','max','step'])if(c[a]!==undefined)input[a]=c[a];}input.value=settings[c.id]??c.default??c.min??'';input.onchange=()=>{controller.pause();serial(()=>controller.setSettings({[c.id]:c.type==='range'?+input.value:input.value}));};label.append(input);host.append(label);}for(const [key,action]of Object.entries(s.actions||{})){const b=document.createElement('button');b.textContent=key==='flee'?'Preview wildlife fleeing':key;b.onclick=()=>serial(async()=>{controller.pause();await controller.invokeAction(key);controller.game.render();});host.append(b);}if(!host.children.length)host.textContent='Use the scenario list to choose another fight or performance.';}
async function loadNow(id,options={}){const s=registry.find(s=>s.id===id);if(!s)throw Error(`Unknown scenario: ${id}`);busy=true;$('loading').hidden=false;actorPanel?.stop();controller.deactivate();specialist?.dispose?.();specialist=null;try{current=s;section=s.section;document.body.classList.remove('nav-open');$('scene-title').textContent=s.label;$('description').textContent=s.description;$('breadcrumb').textContent=`${sections.find(x=>x[0]===section)?.[1]||section} / ${groups[s.group]||'Tools'}`;const full=registry.find(x=>x.section===section&&x.kind==='full');$('full-level').hidden=!full;$('full-level').onclick=()=>{load(full.id).then(()=>controller.play());};$('viewport-wrap').hidden=isTool();$('runtime-tools').hidden=isTool();$('timeline').hidden=isTool();$('controls-help').hidden=isTool();$('focus-status').hidden=isTool();$('specialist-host').hidden=!isTool();$('inspector').hidden=isTool();
 if(isTool()){specialist=await mountSpecialist({kind:s.toolKind||section,host:$('specialist-host'),game:controller.game,baseURL,settings:options.settings||{}});if(options.settings)await specialist.setSettings?.(options.settings);if(options.t)await specialist.seek?.(options.t);}
 else{await controller.load(s,{...(s.routeStart!==undefined?{routeX:s.routeStart}:{}),...options.settings,seed:Number(options.seed??541)});if(options.t)await controller.seek(options.t);inspector();}
 navigation();if(options.history!==false)routeHistory(options.replace);notify(isTool()?'Specialist tools ready.':'Ready · sandbox progression only');fit();}finally{busy=false;$('loading').hidden=true;readout(true);}}
function load(id,options={}){return serial(()=>loadNow(id,options));}
function saveData(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.click();}
function downloadJSON(obj,name){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));saveData(url,name);setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function capture(download=true){const s=isTool()?{...controller.snapshot(),...specialist?.snapshot?.()}:controller.snapshot(),data=isTool()?await specialist?.capture?.():controller.capture();if(!data)throw Error('This tool has no image to capture');const name=`${current.id.replaceAll('/','-')}-${s.tick}`;if(download){saveData(data,name+'.png');downloadJSON({scenario:current.id,tick:s.tick,seed:s.seed,settings:s.settings},name+'.json');}return{image:data,metadata:{scenarioId:current.id,tick:s.tick,seed:s.seed,settings:s.settings}};}
async function contactSheet(from,to,every){if(isTool())throw Error('Choose a game scenario to capture its timeline.');from=Math.max(0,Math.floor(from));to=Math.max(from,Math.floor(to));every=Math.max(1,Math.floor(every));const count=Math.floor((to-from)/every)+1;if(count>120)throw Error('Choose an interval containing at most 120 captures.');const original=controller.snapshot(),scale=+$('scale').value,w=480*scale,h=270*scale,cols=Math.min(4,count),c=document.createElement('canvas');c.width=cols*w;c.height=Math.ceil(count/cols)*(h+24);const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle='#14191f';ctx.fillRect(0,0,c.width,c.height);controller.pause();try{for(let i=0;i<count;i++){await controller.seek(from+i*every);const im=new Image();im.src=controller.capture();await im.decode();const x=i%cols*w,y=Math.floor(i/cols)*(h+24);ctx.drawImage(im,x,y,w,h);ctx.fillStyle='#e8c28a';ctx.font='14px system-ui';ctx.fillText(`Frame ${from+i*every}`,x+8,y+h+17);notify(`Capturing ${i+1} / ${count}`);}saveData(c.toDataURL('image/png'),current.id.replaceAll('/','-')+'-contact-sheet.png');downloadJSON({scenarioId:current.id,from,to,every,seed:original.seed,settings:original.settings},'contact-sheet.json');}finally{await controller.seek(original.tick);notify('Contact sheet saved.');}}
function resolveLocation(){const q=new URLSearchParams(location.search);let settings={};try{const v=JSON.parse(q.get('settings')||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))settings=v;}catch{}if(q.get('presentation'))settings.presentation=q.get('presentation');if(q.get('option')||q.get('variant'))settings.variant=q.get('variant')||q.get('option');return{settings,id:q.get('scenario')||prefs().id||'train/yard',t:Math.max(0,Number(q.get('t'))||0),seed:q.get('seed')||541,mode:q.get('mode')||prefs().mode||'play'};}
async function boot(){controller=await createController(frame,force=>readout(force));registry=[...await createScenarioRegistry(controller.game),...toolEntries];actorPanel=await mountActors($('actor-controls'),controller.game,()=>controller.pause());const loc=resolveLocation();if(!registry.some(s=>s.id===loc.id))loc.id='train/yard';mode=loc.mode;document.body.classList.toggle('inspect',mode==='inspect');$('mode-play').setAttribute('aria-pressed',String(mode!=='inspect'));$('mode-inspect').setAttribute('aria-pressed',String(mode==='inspect'));$('sound').checked=prefs().sound!==false;controller.setMuted(!$('sound').checked);await loadNow(loc.id,{...loc,replace:true});
 window.__review={game:controller.game,listScenarios:()=>registry.map(({load,applySettings,actions,scriptedInput,...s})=>s),load,play:()=>{actorPanel.stop();return isTool()?specialist?.play?.():controller.play();},pause:()=>{actorPanel.stop();return isTool()?specialist?.pause?.():controller.pause();},restart:()=>serial(()=>isTool()?specialist?.restart?.():controller.restart()),seek:t=>serial(()=>isTool()?specialist?.seek?.(t):controller.seek(t)),step:n=>serial(()=>isTool()?specialist?.step?.(n):controller.step(n)),snapshot:()=>isTool()?{scenarioId:current.id,settings:{},...(specialist?.snapshot?.()||{tick:0,playing:false})}:controller.snapshot(),setSettings:s=>serial(()=>isTool()?specialist?.setSettings?.(s):controller.setSettings(s)),setMode:changeMode,setScale:n=>{$('scale').value=n==1||n==2?String(n):'fit';fit();},capture,contactSheet:(a,b,c=3)=>serial(()=>contactSheet(a,b,c)),input:controller.input,selectActor:(k,a)=>actorPanel.select(k,a)};
}
$('mode-play').onclick=()=>changeMode('play');$('mode-inspect').onclick=()=>changeMode('inspect');$('nav-toggle').onclick=()=>document.body.classList.toggle('nav-open');$('inspector-toggle').onclick=()=>document.body.classList.toggle('inspector-open');$('search').oninput=navigation;$('group-filter').onchange=navigation;$('play').onclick=()=>{actorPanel?.stop();controller.snapshot().playing?controller.pause():controller.play();};$('reset').onclick=()=>serial(()=>controller.restart());$('sound').onchange=()=>{controller.setMuted(!$('sound').checked);remember();};$('speed').onchange=()=>controller.setSpeed($('speed').value);$('checkpoint').onchange=()=>{if($('checkpoint').value!=='')serial(async()=>{await controller.seek(+$('checkpoint').value);routeHistory(true);});};$('frame-number').onchange=()=>serial(async()=>{await controller.seek(+$('frame-number').value);routeHistory(true);});let scrubTimer;$('time').oninput=()=>{clearTimeout(scrubTimer);const t=+$('time').value;const version=++navVersion;scrubTimer=setTimeout(()=>serial(async()=>{if(version!==navVersion)return;await controller.seek(t);routeHistory(true);}),80);};for(const b of document.querySelectorAll('[data-step]'))b.onclick=()=>serial(()=>controller.step(+b.dataset.step));$('seed').onchange=()=>load(current.id,{seed:+$('seed').value});$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(new URL(linkURL(),baseURL).href);notify('Scene link copied.');}catch{notify(new URL(linkURL(),baseURL).href);}};$('save-frame').onclick=()=>capture().catch(error);$('contact-sheet').onclick=()=>serial(()=>contactSheet(+$('capture-from').value,+$('capture-to').value,+$('capture-every').value));window.addEventListener('resize',fit);window.addEventListener('popstate',()=>{const loc=resolveLocation();changeMode(loc.mode,false);load(loc.id,{...loc,history:false});});window.addEventListener('beforeunload',()=>{controller?.dispose();actorPanel?.dispose();specialist?.dispose?.();});// The Play/Pause click owns its toggle; focus must not pause it first and make the click restart playback.
document.addEventListener('focusin',()=>{if(document.activeElement!==frame&&document.activeElement!==$('play')&&controller?.snapshot().playing)controller.pause();});boot().catch(error);
