const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1100,height:720}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8011/');await p.waitForFunction(()=>window.__game?.G.state==='welcome');await p.keyboard.press('KeyQ');await p.waitForFunction(()=>window.__game.G.state==='title');await p.waitForTimeout(700);
const results=await p.evaluate(()=>{const g=window.__game,G=g.G,out=[];const tap=a=>{g.press(a);g.step(1);g.release(a);g.step(1);};
tap('pause');out.push(['title ignores pause',!G.paused&&G.state==='title'&&!G.transition]);
for(const state of ['hub','travel','loading','intro','bossintro','clear','ending','over','play']){
 g.resetInput();G.paused=false;if(state==='hub')g.hub();else if(state==='travel')g.travel();else if(state==='loading')g.loading();else if(state!=='title')g.stage(0);G.state=state;G.transition=null;
 tap('pause');const t=G.rawTime,time=G.time;g.step(20);out.push([state,G.paused&&G.rawTime===t&&G.time===time]);tap('pause');out.push([state+' resume',!G.paused]);
}g.hub();G.transition={t:3,dur:100,then:()=>{}};tap('pause');g.step(5);out.push(['transition frozen',G.transition.t===3]);G.transition=null;g.render();return out;});assert(results.every(x=>x[1]),JSON.stringify(results));await p.locator('#game').screenshot({path:'/tmp/gachi-menu.png'});
await p.keyboard.press('Escape');await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>__game.G.paused),false);await p.keyboard.press('Escape');await p.waitForTimeout(100);const box=await p.locator('#game').boundingBox();await p.mouse.click(box.x+box.width*.5,box.y+box.height*125/270);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>__game.G.paused),false);assert.deepEqual(errors,[]);console.log(JSON.stringify({results,mouseResume:true,errors}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
