const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});try{
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const NativeAudio=window.Audio;window.musicAuditElements=[];window.Audio=function(...args){const a=new NativeAudio(...args);window.musicAuditElements.push(a);return a;};window.Audio.prototype=NativeAudio.prototype;});
await page.goto((process.env.GAME_URL||'http://localhost:8011')+'/?auto=walk');await page.waitForFunction(()=>window.__game?.G.state==='play',null,{timeout:90000});await page.evaluate(()=>{__game.G.freezeTime=true;});
const report=await page.evaluate(async()=>{
const {audio}=await import('/js/audio.js'),{STAGES}=await import('/js/stages.js'),{musicGroups}=await import('/js/music_library.js');
const manifest=await(await fetch('/audio/manifest.json',{cache:'reload'})).json();const files=Object.entries(manifest).filter(([,file])=>typeof file==='string'&&file.endsWith('.mp3'));
const tracks=await Promise.all(files.map(async([slot,file])=>{const a=musicAuditElements.find(a=>a.src.endsWith('/'+file));if(!a)return {slot,file,error:'Audio element missing'};if(a.readyState<1)await new Promise(resolve=>{const timeout=setTimeout(resolve,15000);a.addEventListener('loadedmetadata',()=>{clearTimeout(timeout);resolve();},{once:true});a.addEventListener('error',()=>{clearTimeout(timeout);resolve();},{once:true});});return {slot,file,duration:a.duration,readyState:a.readyState,error:a.error?.message||null,loop:a.loop};}));
audio.unlock();await new Promise(r=>setTimeout(r,400));audio.music(null);
for(const row of tracks){audio.play(row.slot);const a=musicAuditElements.find(a=>a.src.endsWith('/'+row.file));await new Promise(r=>setTimeout(r,250));row.playing=!!a&&!a.paused&&a.currentTime>0;row.playbackTime=a?.currentTime;audio.music(null);}
const {readProgress}=await import('/js/progress.js');const migrated=readProgress({version:2,tracks:{heard:['refund_b','stage3b'],pending:['refund_b'],unseen:['stage3b']}},STAGES);
const normalSlots=audio.tracks();audio.music('train_a');audio.music('lair');await new Promise(r=>setTimeout(r,350));const afterRapidSwitch=audio.tracks();audio.music(null);
return {tracks,migrated,rapidSwitch:{before:normalSlots,after:afterRapidSwitch,lost:normalSlots.filter(s=>!afterRapidSwitch.includes(s))},playableSlots:audio.tracks(),library:musicGroups().map(g=>({place:g.title,tracks:g.tracks.map(t=>({slot:t.slot,name:t.name}))})),routes:STAGES.map(s=>({id:s.id,start:s.music,second:s.musicB,switchAt:s.musicBX,boss:s.bossMusic,minibosses:s.minibossMusic,final:!!s.final})),unfilled:Object.entries(manifest).filter(([,v])=>v===null).map(([k])=>k),silent:manifest.silent};});report.errors=errors;fs.mkdirSync('tmp/review/music',{recursive:true});fs.writeFileSync('tmp/review/music/audit.json',JSON.stringify(report,null,2));assert.equal(report.tracks.length,12); assert.ok(report.tracks.every(t=>t.playing&&t.loop&&!t.error)); assert.deepEqual(report.rapidSwitch.lost,[]); for(const key of ['tracksHeard','tracksNew','tracksUnseen']) assert.deepEqual(report.migrated[key],['refund_a']); const refund=report.routes.find(s=>s.id==='refund'); assert.equal(refund.start,'refund_a'); assert.equal(refund.boss,'refund_boss'); assert.equal(refund.second,undefined); const names=report.library.flatMap(g=>g.tracks); assert.equal(names.find(t=>t.slot==='refund_a').name,'ESCALATION'); assert.ok(!names.some(t=>t.slot==='refund_b')); assert.deepEqual(errors,[]); console.log('PASS: all 12 tracks play and loop, rapid switching retains tracks, Refund uses one stage theme and its boss theme');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
