const assert=require('node:assert/strict'),fs=require('node:fs'),s=require('./studio_helper.cjs');
(async()=>{const{page,errors,close}=await s.launch();try{await s.openStudio(page,'delhi/vendor/furnace');const checks=await s.game(page,async(g,G)=>{
 const{startSuper}=await g.importModule('js/player.js'),{getFrame}=await g.importModule('js/sprites.js'),{vendorSpicyFrame}=await g.importModule('js/vendor_inferno.js');const checks=[],ok=(n,v)=>checks.push([n,!!v]);
 for(const phase of [1,2,3])for(const variant of [0,1])for(const guarded of [false,true]){
  g.indiaScene('delhi','vendor',0);g.resetInput();const b=G.boss,p=G.player;Object.assign(b,{phase,phaseTwo:phase>1,mutated:phase===3,inferno:phase===3,lastOrder:phase===3,hp:b.maxhp*(phase===3?.55:phase===2?.7:1),state:'idle',t:0,atkCd:9999,guard:guarded?4:0,protectedStagger:guarded?0:120,x:G.camLock+250,y:226,face:-1});Object.assign(p,{x:b.x-60,y:b.y,state:'idle',face:1});G.meter=100;
  const base=b.delhi.superFrame,calls=[];b.delhi={...b.delhi,superFrame(b,pose){const f=base(b,pose),name=phase===3?'demon_'+(pose.name==='idle'?'idle3':pose.name):pose.name,raw=getFrame(b.set,name,pose.idx,b.face),expected=phase===2?vendorSpicyFrame(raw):raw;calls.push({name,correct:f===expected});return f;}};
  ok(`phase ${phase}, super ${variant}, ${guarded?'guarded':'open'}: activates`,startSuper(p));p.superMove=variant;let retained=true;for(let i=0;i<190;i++){g.step(1);g.render();retained=retained&&b.phase===phase&&b.mutated===(phase===3)&&b.inferno===(phase===3);}
  ok(`phase ${phase}, super ${variant}, ${guarded?'guarded':'open'}: actual renderer uses correct form`,calls.length>0&&calls.every(c=>c.correct));ok(`phase ${phase}, super ${variant}, ${guarded?'guarded':'open'}: phase retained through recovery`,retained&&p.state!=='special'&&!b.superLocked);
 }
 const{vendorCombatFrame}=await g.importModule('js/vendor_boss.js');const b=G.boss;Object.assign(b,{mutated:true,inferno:true});ok('unknown super reaction falls back to enlarged hurt pose',vendorCombatFrame(b,'super_reaction',0)===getFrame(b.set,'demon_hurt',0,b.face));ok('unknown status never falls back to small body',vendorCombatFrame(b,'blind',0)===getFrame(b.set,'demon_hurt',0,b.face));
 return checks;});assert(checks.every(x=>x[1]),JSON.stringify(checks.filter(x=>!x[1])));assert.deepEqual(errors,[]);fs.mkdirSync('tmp/review/pappu-super-form',{recursive:true});fs.writeFileSync('tmp/review/pappu-super-form/checks.json',JSON.stringify(checks,null,2));
 for(const phase of [2,3]){await s.load(page,'delhi/vendor/furnace');await s.game(page,async(g,G,phase)=>{g.indiaScene('delhi','vendor',0);const b=G.boss,p=G.player;Object.assign(b,{phase,phaseTwo:true,mutated:phase===3,inferno:phase===3,lastOrder:phase===3,hp:b.maxhp*(phase===3?.55:.7),state:'idle',guard:0,protectedStagger:120,atkCd:9999,x:G.camLock+250,y:226,face:-1});Object.assign(p,{x:b.x-60,y:b.y,state:'idle',face:1});G.meter=100;const{startSuper}=await g.importModule('js/player.js');startSuper(p);p.superMove=0;},phase);for(let t=0;t<=170;t++){if(t)await s.step(page,1);await s.capture(page,`tmp/review/pappu-super-form/p${phase}-${String(t).padStart(3,'0')}.png`,2);}}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({checks:checks.length,frames:342,errors}));}finally{await close();}})().catch(e=>{console.error(e);process.exitCode=1});
