// Actual devour/smash mutation, jump-only shockwave, persistent destruction and final combat.
const assert=require('node:assert/strict'),fs=require('node:fs'),s=require('./studio_helper.cjs');
(async()=>{const {page,errors,close}=await s.launch();try{
 await s.openStudio(page,'delhi/vendor');const checks=await s.game(page,async(g,G)=>{
 const {VENDOR_CAULDRON:C,vendorChoose,vendorPose,drawKadai}=await g.importModule('js/vendor_boss.js'),{updateBoss}=await g.importModule('js/bosses.js'),{getAIFrame}=await g.importModule('js/aiframes.js'),{drawKadaiSmoke}=await g.importModule('js/vendor_kitchen_life.js'),out=[],ok=(n,v)=>out.push([n,!!v]);
 const setup=(jump=false,guard=false)=>{g.indiaScene('delhi','vendor',0);g.resetInput();const b=G.boss;Object.assign(b,{phase:2,phaseTwo:true,state:'lastorder',t:C.release-1,x:2994,y:218,face:1,pattern:'cauldron'});b.kadai.bowlLifted=true;Object.assign(G.player,{x:b.x-100,y:218,z:jump?30:0,hp:100,invuln:0,dying:false,state:guard?'parry':'idle',guardWindow:guard?12:0});return b;};const tick=()=>{G.time++;G.rawTime++;updateBoss();};
 let b=setup();for(let i=0;i<60;i++)tick();ok('ground shockwave hits once',G.player.hp===82&&b.wave.hit);ok('bowl permanently shattered at smash',b.kadai.smashed&&b.kadai.stoveDestroyed&&b.kadai.broken&&!b.kadai.bowlLifted&&!b.cauldronShot);const wreckCanvas=document.createElement('canvas');wreckCanvas.width=480;wreckCanvas.height=270;const wx=wreckCanvas.getContext('2d');drawKadai(wx,b.kadai,G.camLock);const px=wx.getImageData(0,0,480,270).data;let blue=0;for(let i=0;i<px.length;i+=4)if(px[i+3]&&px[i+2]>120&&px[i+2]>px[i]*1.4&&px[i+2]>px[i+1]*1.15)blue++;ok('destroyed stove renders no blue gas flame',blue===0);
 b=setup(false,true);g.press('parry');for(let i=0;i<60;i++)tick();ok('smash cannot be blocked or parried',G.player.hp===82&&G.player.lastDefense!=='parry');g.resetInput();
 b=setup(true);for(let i=0;i<100;i++)tick();ok('jump clears shockwave',G.player.hp===100);while(b.phase!==3&&b.t<130)tick();ok('mutant form and renewed guard follow smash',b.phase===3&&b.mutated&&b.inferno&&b.guard===4&&!b.wave);
 for(const x of [G.camLock+60,G.camLock+200,G.camLock+410]){G.player.x=x;for(let n=0;n<20;n++){const pick=vendorChoose(b);ok('destroyed cauldron never used for food '+x+':'+n,!['scoop','naan'].includes(pick));b.lastPick=pick;}}
 g.indiaScene('delhi','vendor',0);b=G.boss;Object.assign(b,{phase:2,phaseTwo:true,hp:1,state:'idle',atkCd:999});G.player.invuln=99999;const states=new Set();for(let i=0;i<700&&b.phase!==3;i++){g.step(1);states.add(b.state);}ok('devour smash mutation run without retrieval',states.has('lastorder')&&states.has('mutate')&&!states.has('pot-retrieve')&&b.phase===3&&b.kadai.smashed);
 const hp=b.hp;Object.assign(b,{state:'mutate',t:20});b.hurt(20,1,true,false);ok('mutation cannot be interrupted',b.hp===hp);
 const {FLOOR_FIRE}=await g.importModule('js/vendor_floor_fire.js');Object.assign(b,{state:'breath',pattern:'breath',t:FLOOR_FIRE.end-1,face:-1,lane:b.y});g.step(1);ok('final floor fire ends in its own recovery, no cough',b.state==='recover'&&b.recovery===FLOOR_FIRE.recovery);
 ok('four progressive chug growth poses',getAIFrame('ic_vendor','devour_growth')?.f.length===4);ok('fully grown downward drive',getAIFrame('ic_vendor','smash_drive')?.f.length===3);ok('all devour poses registered',getAIFrame('ic_vendor','devour_smash')?.f.length===8);
 for(const state of ['idle3','walk3','string','breath','flop_polish','flopup','hurt','block','guardbreak','stagger_polish','bump','brutal'])ok('consistent demon family '+state,!!getAIFrame('ic_vendor','demon_'+state));
 const c=document.createElement('canvas');c.width=120;c.height=140;const ctx=c.getContext('2d'),smoke=t=>{G.time=t;ctx.clearRect(0,0,120,140);drawKadaiSmoke(ctx,60,130);return c.toDataURL();};ok('thick smoke animates deterministically',smoke(0)!==smoke(20)&&smoke(20)===smoke(20));
 Object.assign(b,{state:'lastorder',t:82});G.paused=true;g.step(60);ok('pause freezes warning',b.t===82);G.paused=false;return out;
 });assert(checks.every(x=>x[1]),JSON.stringify(checks.filter(x=>!x[1])));const dir='tmp/review/pappu-demon/transition';fs.mkdirSync(dir,{recursive:true});await s.load(page,'delhi/vendor/lastorder');const times=Array.from({length:321},(_,i)=>i);
 for(const t of times){await s.seek(page,t);await s.game(page,(g,G)=>{G.shake=G.flash=G.fade=0;g.render();});await s.capture(page,`${dir}/${String(t).padStart(3,'0')}.png`,2);}
 assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/checks.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,frames:times.length,dir,errors}));
}finally{await close();}})().catch(e=>{console.error(e);process.exitCode=1});
