const assert=require('node:assert/strict'),fs=require('node:fs'),s=require('./studio_helper.cjs');
(async()=>{const{page,errors,close}=await s.launch();try{await s.openStudio(page,'delhi/vendor/scoop');const checks=await s.game(page,async(g,G)=>{
 const{spawnArc,spawnZone,updateShots,VENDOR_OIL_LANDING_GRACE}=await g.importModule('js/shots.js'),{laneMin}=await g.importModule('js/engine.js'),{updatePlayer}=await g.importModule('js/player.js'),{updateBoss}=await g.importModule('js/bosses.js');const{vendorChoose,VENDOR_OIL_VOLLEYS}=await g.importModule('js/vendor_boss.js');const{SPICY_THROW}=await g.importModule('js/vendor_spicy_throw.js');const{ASSETS}=await g.importModule('js/assets.js');const checks=[],ok=(n,v)=>checks.push([n,!!v]);
 const reset=()=>{g.indiaScene('delhi','vendor',0);g.resetInput();Object.assign(G.boss,{state:'idle',atkCd:99999});Object.assign(G.player,{x:G.camLock+140,y:226,z:0,state:'idle',hp:100,invuln:0,vendorOilGrace:0,vendorOilX:G.camLock+140,vendorOilY:226});G.shots=[];G.zones=[];return G.player;};const tick=()=>{G.time++;G.rawTime++;G.hitstop=0;updateShots();};const oil=(p,z=0)=>spawnArc('oil',p.x,p.y,0,0,10,'fire',{source:G.boss,z,jumpSafe:true});
 for(const height of [0,1,10,30,60]){const p=reset();Object.assign(p,{state:'jump',z:height});oil(p,height);tick();ok(`jump clears a colliding oil glob at height ${height}`,p.hp===100);}
 let p=reset();oil(p);tick();ok('grounded player still takes the lob hit',p.hp===90);
 p=reset();Object.assign(p,{state:'jump',z:5});oil(p,30);tick();ok('jump registers an evaded glob',G.shots[0].jumpEvaded);Object.assign(p,{state:'idle',z:0,vendorOilGrace:0});Object.assign(G.shots[0],{z:0,vz:0});tick();ok('evaded glob cannot catch the same player on landing',p.hp===100);
 p=reset();Object.assign(p,{state:'jump',z:1});tick();Object.assign(p,{state:'idle',z:0});oil(p);tick();ok('landing grace also protects against a following lob',p.hp===100&&p.vendorOilGrace===VENDOR_OIL_LANDING_GRACE-1);
 p=reset();Object.assign(p,{state:'jump',z:20});spawnZone('fire',p.x,p.y,22,240,{jumpSafe:true});tick();Object.assign(p,{state:'idle',z:0});for(let i=0;i<80;i++)tick();ok('landing and standing in a cleared patch never burns',p.hp===100);
 p.x+=40;tick();p.x-=40;p.state='walk';tick();ok('walking back into the same patch burns',p.hp===96);
 p=reset();const x=p.x+50;spawnZone('fire',x,p.y,22,240,{jumpSafe:true});tick();p.x=x;p.state='walk';tick();ok('walking into an existing patch burns on entry',p.hp===96);
 p=reset();spawnZone('fire',p.x,p.y,22,240,{jumpSafe:true});for(let i=0;i<60;i++)tick();ok('new floor fire under a stationary player adds no surprise damage',p.hp===100);
 p=reset();Object.assign(p,{state:'jump',z:20});tick();Object.assign(p,{state:'idle',z:0});spawnZone('fire',p.x+50,p.y,22,240,{jumpSafe:true});tick();p.x+=50;p.state='walk';tick();ok('grace applies to adjacent overlapping fire patches',p.hp===100);p.x-=50;tick();for(let i=0;i<24;i++)tick();p.x+=50;tick();ok('walking entry is dangerous again after grace expires',p.hp===96);
 p=reset();spawnZone('fire',p.x+50,p.y,22,1,{jumpSafe:true});p.x+=50;p.state='walk';tick();ok('extinguished oil cannot burn on entry',p.hp===100);
 p=reset();spawnZone('fire',p.x,p.y,22,240);for(let i=0;i<24;i++)tick();ok('unrelated fire hazards preserve their existing damage',p.hp===96);
 p=reset();Object.assign(p,{state:'jump',z:1});tick();g.press('pause');g.step(1);g.release('pause');const grace=p.vendorOilGrace;g.step(40);ok('pause freezes landing grace',p.vendorOilGrace===grace);
 for(const phase of [1,2]){p=reset();const b=G.boss;Object.assign(b,{phase,state:'fling',pattern:'scoop',t:phase===2?SPICY_THROW.release-1:13,x:p.x+80});G.time++;updateBoss();ok(`phase ${phase} actual oil volley carries jump protection`,G.shots.length===(phase===2?SPICY_THROW.n:3)&&G.shots.every(x=>x.jumpSafe));}
 p=reset();Object.assign(p,{state:'jump',z:.1,vz:4.85,t:0});spawnArc('oil',p.x,p.y,0,2.2,10,'fire',{source:G.boss,z:92,jumpSafe:true});let safe=true;for(let i=0;i<100;i++){G.time++;G.hitstop=0;updatePlayer(p);updateShots();safe=safe&&p.hp===100;}ok('normal jump through a full oil arc and landing is safe',safe&&G.zones.length===1&&G.zones[0].jumpSafe);
 for(const phase of [1,2])for(const gap of [35,90,220,380]){p=reset();const b=G.boss;Object.assign(b,{phase,turn:0,lastPick:null});p.x=b.x-gap;let noBread=true,oil=0;for(let i=0;i<80;i++){const pick=vendorChoose(b);noBread&&=pick!=='naan';oil+=pick==='scoop';b.lastPick=pick;}ok(`phase ${phase}, range ${gap}: oil replaces bread throughout rotation`,noBread&&oil>0);}
 p=reset();let b=G.boss;Object.assign(b,{phase:2,state:'fling',pattern:'scoop',t:SPICY_THROW.release-1,x:p.x+100});G.time++;updateBoss();ok('chilli hurls a fan of five small jump-safe globs, no oversized bomb',G.shots.length===5&&G.shots.every(s=>!s.oilBomb&&s.visualScale<=1.1&&s.jumpSafe&&s.dmg===SPICY_THROW.dmg));ok('chilli has one committed hurl',VENDOR_OIL_VOLLEYS[1].length===1);ok('target rings and splashes agree',b.flingTo.radius===SPICY_THROW.radius&&G.shots.every(s=>s.burstRadius===SPICY_THROW.radius));ok('chilli hurl winds up longer than the lunch-rush lob',SPICY_THROW.release-VENDOR_OIL_VOLLEYS[0][0].at>=10);
 for(const at of [-60,0,60]){p=reset();p.x+=at;b=G.boss;Object.assign(b,{phase:2,state:'fling',pattern:'scoop',t:0,x:G.camLock+380});let jumpT=-1,safe=true;for(let i=0;i<110;i++){if(jumpT<0&&G.shots.length&&G.shots.some(s=>s.z<40)){jumpT=i;Object.assign(p,{state:'jump',z:.1,vz:4.85,t:0});}G.time++;G.rawTime++;G.hitstop=0;updatePlayer(p);updateBoss();updateShots();safe&&=p.hp===100;}ok(`one timed jump clears the whole fan and its splashes (offset ${at})`,safe&&G.zones.filter(z=>z.jumpSafe).length===5);}
 p=reset();b=G.boss;Object.assign(b,{phase:2,state:'fling',pattern:'scoop',t:0,x:G.camLock+380});const lands=[];for(let i=0;i<110;i++){const before=G.zones.length;Object.assign(p,{invuln:999});G.time++;G.rawTime++;G.hitstop=0;updateBoss();updateShots();if(G.zones.length>before)lands.push(i);}ok('splats roll out within a quarter second',lands.length&&lands.at(-1)-lands[0]<=15);
 p=reset();b=G.boss;Object.assign(b,{phase:2,state:'fling',pattern:'scoop',t:0,x:G.camLock+380});p.y=laneMin(p.x)+2;let walked=true;for(let i=0;i<110;i++){if(i>=SPICY_THROW.release+2&&i<SPICY_THROW.release+20)p.y+=2.2;G.time++;G.rawTime++;G.hitstop=0;updateBoss();updateShots();}ok('stepping out of the lane after the snap also avoids the fan',p.hp===100);
 const voice=G.audio.voice,played=[];G.audio.voice=id=>played.push(id);try{p=reset();b=G.boss;Object.assign(b,{phase:1,state:'rage',t:79,hp:b.maxhp*.6});G.time++;updateBoss();p=reset();b=G.boss;Object.assign(b,{phase:2,state:'mutate',t:37,hp:b.maxhp*.5});G.time++;updateBoss();ok('both transformation stingers omit spoken Duke quotes',played.length===0);}finally{G.audio.voice=voice;}
 return checks;});assert(checks.every(x=>x[1]),JSON.stringify(checks));assert.deepEqual(errors,[]);fs.mkdirSync('tmp/review/pappu-oil-fairness',{recursive:true});fs.writeFileSync('tmp/review/pappu-oil-fairness/checks.json',JSON.stringify(checks,null,2));console.log(JSON.stringify({checks:checks.length,errors}));}finally{await close();}})().catch(e=>{console.error(e);process.exitCode=1});
