const assert=require('node:assert/strict'),fs=require('node:fs'),s=require('./studio_helper.cjs');
(async()=>{const{page,errors,close}=await s.launch();try{
 await s.openStudio(page,'delhi/vendor/lastorder');const checks=await s.game(page,async(g,G)=>{
 const{updateBoss}=await g.importModule('js/bosses.js'),{vendorChoose,VENDOR_PHASE}=await g.importModule('js/vendor_boss.js'),out=[],ok=(n,v)=>out.push([n,!!v]);
 const setup=()=>{g.indiaScene('delhi','vendor',0);g.resetInput();const b=G.boss;Object.assign(b,{state:'idle',atkCd:999});Object.assign(G.player,{hp:100,invuln:0,z:0,state:'idle'});return b;};const tick=()=>{G.time++;G.rawTime++;G.hitstop=0;updateBoss();};
 let b=setup();b.hp=Math.floor(b.maxhp*.51);tick();ok('normal phase lasts until half health',b.phase===1&&b.state==='idle');b.hp=Math.floor(b.maxhp*.5);tick();ok('half health begins chilli feast',b.state==='rage');const chilliHeal=[];for(let i=0;i<110;i++){tick();chilliHeal.push(b.hp);}ok('chilli feast regrows health steadily to seventy percent',chilliHeal.some(h=>h>b.maxhp*.5&&h<b.maxhp*.7)&&chilliHeal.every((h,i)=>!i||h>=chilliHeal[i-1])&&b.phase===2&&b.hp===Math.round(b.maxhp*.7)&&!b.mutated);for(let i=0;i<12;i++)tick();ok('restored health cannot retrigger the chilli transition',b.phase===2&&b.state==='idle');b.atkCd=999;b.hp=Math.floor(b.maxhp*.31);tick();ok('phase two remains active above thirty percent',b.phase===2&&b.state==='idle');
 b.state='idle';b.hp=20;b.guard=0;b.hurt(30,-1,true,false);ok('phase two defeat is intercepted without score or cinematic',b.hp===Math.floor(b.maxhp*.3)&&!b.dead&&b.pendingFeast&&!G.india.cinematic);tick();ok('defeat starts a protected knockdown',b.state==='fakeout');const hp=b.hp;b.hurt(20,1,true,false);ok('fake-out cannot be interrupted',b.hp===hp&&!b.dead);let states=new Set(),healing=[];for(let i=0;i<700&&b.phase!==3;i++){states.add(b.state);if(b.state==='lastorder'&&b.t>=28)healing.push(b.hp);tick();}ok('fakeout crawls to pot then devours and mutates', ['fakeout','crawl-feast','lastorder','mutate'].every(x=>states.has(x))&&b.phase===3);ok('final form refills only its final health segment',b.hp===Math.round(b.maxhp*.55)&&b.mutated&&b.inferno&&b.guard===4);ok('health visibly grows throughout eating',healing.length>30&&healing.some(h=>h>b.maxhp*.3&&h<b.maxhp*.55)&&healing.every((h,i)=>!i||h>=healing[i-1])&&healing.at(-1)===Math.round(b.maxhp*.55));ok('pot and stove remain smashed',b.kadai.broken&&b.kadai.stoveDestroyed);let deck=new Set();for(let i=0;i<60;i++)deck.add(vendorChoose(b));ok('final attack set excludes earlier belly attacks', [...deck].every(x=>['forearm','cleaver','breath'].includes(x)));
 b=setup();Object.assign(b,{phase:2,hp:10,guard:0,superLocked:true,superApplying:true});G.player.state='special';b.hurt(30,-1,true,false);tick();ok('fakeout waits for active super to finish',b.pendingFeast&&b.state!=='fakeout'&&!b.dead);G.player.state='idle';tick();ok('fakeout resumes after super releases',b.state==='fakeout'&&!b.dead);
 for(const phase of [2,3])for(const z of [0,1,10,30]){b=setup();Object.assign(b,{phase,state:'breath',pattern:'breath',t:4,lane:226,x:G.camLock+320,y:226,face:-1});Object.assign(G.player,{x:b.x-100,y:226,z,state:'jump',hp:100});for(let i=0;i<12;i++)tick();ok(`phase ${phase} jump skill check protects at height ${z}`,G.player.hp===100);}
 return out;});assert(checks.every(x=>x[1]),JSON.stringify(checks.filter(x=>!x[1])));
 const dir='tmp/review/pappu-fakeout';fs.mkdirSync(dir,{recursive:true});for(const[name,id,max]of [['chilli','delhi/vendor/rage',130],['fakeout','delhi/vendor/lastorder',600]]){await s.load(page,id);await s.game(page,(g,G)=>{G.player.invuln=99999;G.player.invulnFlashAfter=99999;});let states=[];for(let t=0;t<=max;t++){if(t)await s.step(page,1);const st=await s.game(page,(g,G)=>{G.shake=G.flash=0;g.render();return[G.boss.state,G.boss.t,G.boss.x,G.boss.y,G.boss.hp,G.boss.phase];});states.push(st);await s.capture(page,`${dir}/${name}-${String(t).padStart(3,'0')}.png`,2);if(name==='fakeout'&&st[5]===3)break;}fs.writeFileSync(dir+'/'+name+'-states.json',JSON.stringify(states));}
 assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/checks.json',JSON.stringify(checks,null,2));console.log(JSON.stringify({checks:checks.length,errors}));
 }finally{await close();}})().catch(e=>{console.error(e);process.exitCode=1});
