const assert=require('node:assert/strict'),fs=require('node:fs'),s=require('./studio_helper.cjs');
(async()=>{const{page,errors,close}=await s.launch();try{
 await s.openStudio(page,'delhi/vendor/p3-forearm');const checks=await s.game(page,async(g,G)=>{
 const{updateBoss}=await g.importModule('js/bosses.js'),{vendorChoose,vendorPose,VENDOR_WIND}=await g.importModule('js/vendor_boss.js'),FW=VENDOR_WIND.forearm[2],out=[],ok=(n,v)=>out.push([n,!!v]);
 const setup=(pattern,z=0)=>{g.indiaScene('delhi','vendor',0);const b=G.boss;Object.assign(b,{phase:3,inferno:true,mutated:true,state:'windup',pattern,t:0,x:G.camLock+200,y:226,face:1});Object.assign(G.player,{x:b.x+110,y:226,z,state:z?'jump':'idle',hp:100,invuln:0,dying:false});return b;};const tick=()=>{G.time++;G.rawTime++;G.hitstop=0;updateBoss();};
 let b=setup('forearm');const deck=new Set();for(let i=0;i<80;i++)deck.add(vendorChoose(b));ok('final deck only distinct furnace attacks', [...deck].every(x=>['forearm','cleaver','breath'].includes(x))&&deck.size===3);
 b=setup('forearm');for(let i=0;i<FW;i++)tick();ok('forearm has full green warning',b.state==='forearm'&&b.t===0);for(let i=0;i<8;i++)tick();ok('forearm drives forward and hits once',G.player.hp===82&&b.x>G.camLock+200);for(let i=0;i<28;i++)tick();ok('forearm exposes recovery',b.state==='recover');
 b=setup('forearm');Object.assign(G.player,{x:b.x+70,state:'parry',guardWindow:10,face:-1});for(let i=0;i<FW+8;i++)tick();ok('timed forearm parry earns protected opening',G.player.hp===100&&b.protectedStagger>0);
 b=setup('forearm',30);for(let i=0;i<FW+10;i++)tick();ok('forearm can be jumped',G.player.hp===100);
 b=setup('cleaver');for(let i=0;i<42;i++)tick();ok('smash has full red warning',b.state==='cleaver'&&b.t===0);for(let i=0;i<7;i++)tick();ok('smash spawns one substantial floor shockwave',b.wave&&b.wave.damage===18&&b.wave.max===240);for(let i=0;i<10;i++)tick();ok('floor shockwave damages once',G.player.hp===82);ok('tool remains stuck with new crouching pose',b.state==='cleaver-stuck'&&vendorPose(b)[0]==='cleaver');const hp=b.hp;b.hurt(10,-1,true,false);ok('stuck smash can be punished',b.hp<hp&&b.state==='cleaver-stuck');
 b=setup('cleaver',30);for(let i=0;i<70;i++)tick();ok('jump clears floor smash',G.player.hp===100);
 return out;});assert(checks.every(x=>x[1]),JSON.stringify(checks));
 await s.load(page,'delhi/vendor/p3-cleaver');await s.step(page,25);await s.game(page,(g,G)=>Object.assign(G.player,{hp:100,state:'jump',t:0,z:.1,vz:4.85,invuln:0}));let jumpSafe=true;for(let i=0;i<60;i++){await s.step(page,1);jumpSafe=jumpSafe&&await s.game(page,(g,G)=>G.player.hp===100);}assert(jumpSafe,'normal jump at first red cue must clear the complete smash shockwave');checks.push(['normal jump reacting to the red cue clears smash',jumpSafe]);
 const dir='tmp/review/pappu-furnace';fs.mkdirSync(dir,{recursive:true});for(const name of ['forearm','cleaver']){await s.load(page,'delhi/vendor/p3-'+name);await s.game(page,(g,G)=>{G.player.invuln=99999;G.player.invulnFlashAfter=99999;});const states=[];for(let t=0;t<=150;t++){if(t)await s.step(page,1);states.push(await s.game(page,(g,G)=>{G.shake=G.flash=0;g.render();return[G.boss.state,G.boss.t];}));await s.capture(page,`${dir}/${name}-${String(t).padStart(3,'0')}.png`,2);}fs.writeFileSync(`${dir}/${name}-states.json`,JSON.stringify(states));}
 assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/checks.json',JSON.stringify(checks,null,2));console.log(JSON.stringify({checks:checks.length,frames:302,errors}));
 }finally{await close();}})().catch(e=>{console.error(e);process.exitCode=1});
