// Record the real Review Studio at 2x and sample authored boss motion every three ticks.
const fs=require('fs'),{chromium}=require('playwright');
const base=process.env.GAME_URL||'http://localhost:8011';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const page=await browser.newPage({viewport:{width:1300,height:900}});await page.goto(base+'/review.html?scenario=refund%2Fcloser%2Fboxing&mode=inspect');await page.waitForFunction(()=>window.__review?.snapshot().scenarioId==='refund/closer/boxing',null,{timeout:90000});await page.evaluate(()=>{__review.setScale(2);__review.game.G.audio.setMuted?.(true)});
const frame=page.frames().find(f=>f.url().includes('runtime.html'));await frame.evaluate(()=>{const c=document.querySelector('#game'),parts=[],record=new MediaRecorder(c.captureStream(30),{mimeType:'video/webm;codecs=vp9'});record.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};record.onstop=()=>{const b=new Blob(parts,{type:'video/webm'}),r=new FileReader();r.onload=()=>window.__bossVideo=r.result;r.readAsDataURL(b)};window.__bossRecorder=record;record.start()});
for(const [scene,ms]of [['refund/closer/boxing',2900],['refund/closer/handset',2500],['refund/closer/deal',2900],['refund/closer/phase-break',2000],['refund/closer-finish',8700]]){await page.evaluate(async scene=>{await __review.load(scene);__review.play()},scene);await page.waitForTimeout(ms);await page.evaluate(()=>__review.pause());}
await frame.evaluate(()=>__bossRecorder.stop());await frame.waitForFunction(()=>window.__bossVideo);const data=await frame.evaluate(()=>window.__bossVideo);fs.writeFileSync('tmp/review/refund-boss/closer-performance-2x.webm',Buffer.from(data.split(',')[1],'base64'));console.log('tmp/review/refund-boss/closer-performance-2x.webm');
// Contact sheets replay each demonstration normally, sampling every three ticks.
for(const scene of ['boxing','boxing-phase2','deal','handset','phase-break']){await page.evaluate(async scene=>{await __review.load('refund/closer/'+scene)},scene);const data=await frame.evaluate(scene=>{const g=__game,G=g.G,cols=4,count=41,c=document.createElement('canvas');c.width=cols*480;c.height=Math.ceil(count/cols)*288;const x=c.getContext('2d');x.fillStyle='#171b20';x.fillRect(0,0,c.width,c.height);x.font='12px monospace';for(let n=0;n<count;n++){G.shake=G.flash=0;g.render();const cx=n%cols*480,cy=Math.floor(n/cols)*288;x.drawImage(document.querySelector('#game'),cx,cy,480,270);x.fillStyle='#efd5a4';x.fillText(scene+' t'+n*3+' '+G.boss.state+':'+G.boss.t,cx+8,cy+283);g.step(3)}return c.toDataURL()},scene);fs.writeFileSync('tmp/review/refund-boss/'+scene+'-every3ticks.png',Buffer.from(data.split(',')[1],'base64'))}
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
