// Preview selection uses campaign slots; mute, seek and switching cannot retain stale music.
const assert=require('node:assert/strict'),fs=require('node:fs'),studio=require('./studio_helper.cjs');
(async()=>{const {page,errors,close}=await studio.launch();try{
 await studio.openStudio(page,'delhi/vendor');const checks=[];
 const expect=async(id,slot)=>{await studio.load(page,id);assert.equal(await page.evaluate(()=>__review.snapshot().music),slot,id);checks.push(id);};
 for(const [id,slot]of Object.entries({'delhi/vendor':'delhi_vendor','delhi/vendor-intro':'delhi_vendor','delhi/vendor-finish':'delhi_vendor','delhi/vendor/breath':'delhi_vendor','delhi/vendor/p3-forearm':'delhi_vendor','delhi/market':'delhi_a','delhi/ghat':'delhi_b','delhi/dredger':'delhi_boss','delhi/dredger-intro':'delhi_boss','delhi/dredger-finish':'delhi_boss','refund/calling':'refund_a','refund/closer':'refund_boss','refund/closer-intro':'refund_boss','refund/closer-finish':'refund_boss','train/yard':'train_a','train/general':'train_b','train/office':'train_b','train/conductor-fight':'train_b','train/inspector-finish':'train_b','train/boss':'train_boss','train/boss-enraged':'train_boss','train/boss-roof':'train_boss','train/shera-finish':'train_boss','train/knockout':'train_boss','train/escape':'train_boss','trip/penthouse':'lair','trip/lobby':'lobby','trip/elevator':null}))await expect(id,slot);
 await studio.load(page,'delhi/market');await page.evaluate(()=>__review.setSettings({routeX:4300}));assert.equal(await page.evaluate(()=>__review.snapshot().music),'delhi_b');checks.push('route camera follows stage geography');
 await studio.load(page,'delhi/vendor-finish');await studio.seek(page,250);assert.equal(await page.evaluate(()=>__review.snapshot().music),'delhi_vendor');await page.evaluate(()=>__review.restart());assert.equal(await page.evaluate(()=>__review.snapshot().music),'delhi_vendor');checks.push('seek/restart preserves Pappu track');
 await page.locator('#sound').check();await studio.load(page,'refund/closer');await page.locator('#play').click();assert.equal(await page.evaluate(()=>__review.game.G.audio.snapshot().music),'refund_boss');await page.locator('#play').click();
 await page.locator('#sound').uncheck();await studio.load(page,'delhi/vendor');await page.locator('#play').click();await page.locator('#sound').check();assert.equal(await page.evaluate(()=>__review.game.G.audio.snapshot().music),'delhi_vendor');checks.push('unmute starts selected track');await page.locator('#play').click();
 await studio.load(page,'trip/elevator');await page.locator('#play').click();assert.equal(await page.evaluate(()=>__review.game.G.audio.snapshot().music),null);checks.push('silent selection stops old track');await page.locator('#play').click();
 const manifest=JSON.parse(fs.readFileSync('audio/manifest.json'));const all=await page.evaluate(()=>__review.listScenarios().filter(s=>s.kind!=='tool').map(s=>s.id));for(const id of all){await studio.load(page,id);const m=await page.evaluate(()=>__review.snapshot().music);assert(m==null||Object.hasOwn(manifest,m),id+' has valid music slot '+m);}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({explicitChecks:checks.length,scenarios:all.length,errors}));
}finally{await close();}})().catch(e=>{console.error(e);process.exitCode=1});
