const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:980,height:580}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://localhost:8011/?auto=walk');await p.waitForFunction(()=>__game?.G.state==='play');
 const checks=await p.evaluate(async()=>{const g=__game,G=g.G,{sethRetreatPose}=await import('./js/train_finishers.js'),{startTrainCinematic,updateTrain}=await import('./js/train.js');const out=[],ok=(n,v)=>out.push([n,!!v]);
 for(const side of [-1,1]){g.trainScene('boss');const boss=G.boss;G.player.x=boss.x+side*130;boss.roof=true;startTrainCinematic('roof');g.step(30);ok('staged left '+side,G.player.x===7842&&G.train.cinematic.fromBossX===7880);const calls=[],voice=G.audio.voice;G.audio.voice=(n)=>calls.push(n);for(let i=0;i<749;i++)updateTrain();ok('no early pursuit '+side,G.enemies.length===0&&G.train.cinematic?.kind==='roof');updateTrain();ok('one handoff '+side,!G.train.cinematic&&G.train.climbed&&G.boss.trainWaiting);ok('one quote '+side,calls.filter(n=>n==='duke_come_get_some').length===1);G.audio.voice=voice;}
 for(const t of [9,130,210,350,570]){g.trainScene('roof-transition',t);const before=G.train.cinematic.t;G.paused=true;g.step(20);ok('pause '+t,G.train.cinematic.t===before);G.paused=false;}
 let last=0;for(let t=82;t<270;t++){const q=sethRetreatPose(t);ok('forward '+t,q.x>=last);last=q.x;}
 g.trainScene('roof-transition',400);const c=G.train.cinematic,old=JSON.stringify(c,(k,v)=>k==='snapshot'?null:v);g.render();g.render();ok('render pure',old===JSON.stringify(c,(k,v)=>k==='snapshot'?null:v));return out;});assert(checks.every(x=>x[1]),JSON.stringify(checks.filter(x=>!x[1])));
 const dir='tmp/review/seth-retreat';fs.mkdirSync(dir,{recursive:true});
 if(!process.env.NO_CAPTURE)for(let t=0;t<=780;t+=3){await p.evaluate(t=>{__game.trainScene('roof-transition',t);__game.G.shake=0;__game.render()},t);for(const width of (t%30===0?[480,960]:[960])){await p.locator('#game').evaluate((c,w)=>Object.assign(c.style,{width:w+'px',height:w*270/480+'px',maxWidth:'none'}),width);await p.locator('#game').screenshot({path:`${dir}/${t}-${width}.png`});}}
 const missing=await b.newPage();await missing.route(/injured_retreat|injured_climb|seth_jacket/,r=>r.abort());await missing.goto('http://localhost:8011/?auto=walk');await missing.waitForFunction(()=>__game?.G.state==='play');assert(await missing.evaluate(()=>{__game.trainScene('roof-transition',0);__game.step(780);return __game.G.train.climbed&&!__game.G.train.cinematic;}),'missing art completes');await missing.close();
 assert.deepEqual(errors,[]);console.log(JSON.stringify({checks:checks.length,errors,captures:'every three ticks'}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
