const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1000,height:650}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8011/?auto=walk');await p.waitForFunction(()=>__game?.G.state==='play');
const checks=await p.evaluate(async()=>{const g=__game,G=g.G,{startSuper,updatePlayer}=await import('./js/player.js'),{updateEnemies}=await import('./js/enemies.js'),{updateBoss}=await import('./js/bosses.js');const out=[],ok=(n,v)=>out.push([n,!!v]);
g.trainScene('general');G.enemies=[];G.boss=null;G.meter=100;const a=G.player;Object.assign(a,{state:'idle',face:1,lastSuperMove:0});ok('invalid attempt rejected',!startSuper(a));ok('invalid preserves alternation and meter',a.lastSuperMove===0&&G.meter===100);
for(const variant of [0,1]){g.trainScene('general');G.boss=null;G.enemies=[];Object.assign(G.player,{state:'idle',face:1});G.meter=100;const e=g.spawn('nr_tough',50,0);e.hp=200;e.state='idle';startSuper(G.player);G.player.superMove=variant;let wasAir=false,contacts=0,lastV=0;for(let t=0;t<180;t++){updatePlayer(G.player);updateEnemies();if(e.z>0)wasAir=true;if(lastV<0&&e.vz>0)contacts++;lastV=e.vz;}ok('launch '+variant,wasAir);ok('one bounce '+variant,contacts===1);ok('no landing damage '+variant,e.hp===164);}
for(const broken of [false,true]){g.trainScene('conductor',300);G.enemies=[];G.train.officeDeskBroken=broken;const c=G.boss;Object.assign(c,{hp:c.maxhp*.59,state:'idle',t:0,protectedStagger:0,shieldActive:false});G.player.invuln=99999;let protectedTicks=0,whistles=0;const sound=G.audio.roomSfx;G.audio.roomSfx=(n)=>{if(n==='conductor_whistle')whistles++};for(let t=0;t<420;t++){updateBoss();if(c.backupProtected){protectedTicks++;const hp=c.hp;c.hurt(1,1,true,false);ok('rear protected',c.hp===hp);}}
ok('backup once '+broken,c.backup===2&&whistles===1);ok('waits for reinforcements '+broken,protectedTicks>90&&c.backupProtected);c.backupActors.forEach(e=>e.dead=true);for(let t=0;t<120;t++)updateBoss();ok('returns to lane '+broken,!c.backupProtected&&c.y>=210);G.audio.roomSfx=sound;}
g.trainScene('conductor',300);G.enemies=[];let c=G.boss;Object.assign(c,{hp:c.maxhp*.59,state:'stagger',protectedStagger:45});for(let t=0;t<44;t++)updateBoss();ok('backup waits for full punish',c.protectedStagger===1&&!c.backupDone);updateBoss();updateBoss();ok('backup follows punish',c.state==='backup_retreat');
for(const state of ['backup_retreat','backup_call','backup_wait','backup_return']){c.state=state;c.t=5;const before=JSON.stringify([c.x,c.y,c.t]);G.paused=true;g.step(20);ok('pause '+state,JSON.stringify([c.x,c.y,c.t])===before);G.paused=false;}
g.trainScene('conductor',300);G.enemies=[];c=G.boss;Object.assign(c,{hp:c.maxhp*.59,state:'idle',t:0});const support=g.spawn('nr_tough',90,0);updateBoss();ok('existing support defers call',c.state!=='backup_retreat'&&!c.backupDone);support.dead=true;c.state='idle';updateBoss();ok('call after support defeated',c.state==='backup_retreat');
return out;});console.log(JSON.stringify({checks:checks.length,failures:checks.filter(x=>!x[1]),errors}));assert(checks.every(x=>x[1]));assert.deepEqual(errors,[]);if(process.env.NO_CAPTURE)return;
const dir='tmp/review/signature-supers';fs.mkdirSync(dir,{recursive:true});
for(const variant of [0,1]){await p.evaluate(async v=>{const g=__game,G=g.G,{startSuper}=await import('./js/player.js');g.trainScene('general');G.enemies=[];G.props=[];G.boss=null;G.meter=100;G.player.face=1;const e=g.spawn('nr_tough',55,0);e.hp=200;e.state='idle';startSuper(G.player);G.player.superMove=v},variant);
for(let t=0;t<=150;t++){if(t)await p.evaluate(async()=>{const {updatePlayer}=await import('./js/player.js'),{updateEnemies}=await import('./js/enemies.js');updatePlayer(__game.G.player);updateEnemies();(await import('./js/effects.js')).updateEffects();__game.G.time++;__game.G.hitstop=0;__game.G.shake=0;__game.render()});if(t%3===0)for(const w of [480,960]){await p.locator('#game').evaluate((c,w)=>Object.assign(c.style,{width:w+'px',height:w*270/480+'px',maxWidth:'none'}),w);await p.locator('#game').screenshot({path:`${dir}/super-${variant}-${t}-${w}.png`});}}
}
await p.evaluate(()=>{const g=__game,G=g.G;g.trainScene('conductor',300);G.enemies=[];Object.assign(G.boss,{hp:G.boss.maxhp*.59,state:'idle',t:0,protectedStagger:0,shieldActive:false});G.player.x=G.camX+100;G.player.y=230;G.player.invuln=0;G.player.hp=9999});for(let t=0;t<320;t++){await p.evaluate(async()=>{const {updateBoss}=await import('./js/bosses.js');updateBoss();__game.G.shake=0;__game.render()});if(t%12===0)await p.locator('#game').screenshot({path:`${dir}/backup-${t}.png`});}
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
