const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1100,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8011/?auto=travel-curb&t=1');await p.waitForFunction(()=>window.__game?.travelReady());await p.waitForTimeout(500);
const checks=await p.evaluate(async()=>{const g=__game,G=g.G,{nearStreetCar,boardingAt,driveAt,STREET,streetFansAt}=await import('/js/street.js'),{TRAVEL_ART}=await import('/js/travel.js'),out=[];
const check=(n,v)=>out.push([n,!!v]);const fresh=phase=>{g.resetInput();G.freezeTime=false;g.travel(phase);G.fade=0;};const tap=a=>{g.press(a);g.step(1);g.release(a);g.step(1);};
fresh('curb');g.step(140);check('arrival releases control',!G.travel.street.arriving&&G.travel.y===225);g.step(5);check('greeting once',G.travel.street.greeting>=0);let greeting=G.travel.street.greeting;g.step(300);check('greeting not repeated',G.travel.street.greeting===greeting);
const crowd=streetFansAt(G.travel);check('three detailed fans',new Set(crowd.map(f=>f.row)).size===3);check('VIP crowd stays behind playable lane',crowd.every(f=>f.y<196));check('crowd grouped closely',Math.max(...crowd.map(f=>f.x))-Math.min(...crowd.map(f=>f.x))<65);check('expanded character sheet',TRAVEL_ART.fans.width===1280&&TRAVEL_ART.fans.height===576);let flashes=0;for(let clock=0;clock<1000;clock++){for(const f of streetFansAt({t:clock})){if(f.flash){flashes++;check('camera flash matches raised camera',f.row===2&&f.frame===2);}}}check('camera flashes occasionally',flashes>0&&flashes<12);
G.travel.x=402;G.travel.actor.x=402;G.travel.actor.z=20;check('airborne cannot board',!nearStreetCar(G.travel));G.travel.actor.z=0;G.travel.gate=false;check('grounded can board',nearStreetCar(G.travel));tap('use');check('interaction begins boarding',G.travel.phase==='car-board');g.step(STREET.boardDuration);check('boarding reaches drive',G.travel.phase==='drive');g.step(STREET.driveDuration+60);check('drive reaches apron',G.travel.phase==='apron');check('short vista drive keeps smaller car',driveAt(299).w===200&&driveAt(299).x===156);
for(const phase of ['curb','car-board','drive']){fresh(phase);g.step(5);tap('pause');const t=G.travel.t,clock=G.travel.street.clock;g.step(30);check(phase+' pauses',G.paused&&G.travel.t===t&&G.travel.street.clock===clock);tap('pause');g.step(3);check(phase+' resumes',!G.paused&&G.travel.t>t);if(phase!=='curb'){tap('attack');check(phase+' cannot skip',G.travel.phase===phase);}}
fresh('curb');check('repeat resets greeting',G.travel.street.greeting===-1);g.step(140);tap('pause');tap('back');g.step(60);check('quit clears travel',G.state==='title'&&!G.travel);
const railCanvas=document.createElement('canvas');railCanvas.width=TRAVEL_ART.drive_railing.width;railCanvas.height=TRAVEL_ART.drive_railing.height;const railCtx=railCanvas.getContext('2d');railCtx.drawImage(TRAVEL_ART.drive_railing,0,0);const alpha=railCtx.getImageData(0,14,railCanvas.width,24).data;let holes=0;for(let i=3;i<alpha.length;i+=4)if(alpha[i]===0)holes++;check('railing openings are transparent',holes/(alpha.length/4)>.5);
const saved={...TRAVEL_ART};for(const k of Object.keys(TRAVEL_ART))delete TRAVEL_ART[k];for(const phase of ['curb','car-board','drive']){fresh(phase);g.step(150);g.render();}Object.assign(TRAVEL_ART,saved);check('missing art renders safely',true);
fresh('curb');g.step(134);G.travel.x=330;G.travel.actor.x=330;
const pads=navigator.getGamepads.bind(navigator),pad={connected:true,buttons:Array.from({length:16},()=>({pressed:false,value:0})),axes:[1,0,0,0]};navigator.getGamepads=()=>[pad];g.step(12);check('gamepad walks',G.travel.x>330);pad.axes[0]=0;pad.buttons[1]={pressed:true,value:1};g.step(1);check('gamepad jumps',G.travel.actor.z>0||G.travel.actor.vz>0);pad.buttons[1]={pressed:false,value:0};g.step(70);G.travel.x=402;G.travel.actor.x=402;pad.buttons[4]={pressed:true,value:1};g.step(1);check('gamepad boards',G.travel.phase==='car-board');g.step(20);check('held interact does not skip boarding',G.travel.phase==='car-board');navigator.getGamepads=pads;g.resetInput();g.step(1);
fresh('car-board');g.step(60);check('boarding sound cues in order',G.travel.street.events.map(e=>e.name).join(',')==='handle,car_close,ignition');const events=G.travel.street.events.length;g.render();g.render();check('render does not trigger audio',G.travel.street.events.length===events);
check('seat swap is hidden',boardingAt(29).blackout===1&&boardingAt(30).blackout===1&&!boardingAt(29).seated&&boardingAt(30).seated);check('seated driver revealed before ignition',boardingAt(44).blackout===0&&boardingAt(44).seated&&!boardingAt(44).lights&&boardingAt(48).lights);check('boarding lasts 1.3 seconds',STREET.boardDuration===78);G.freezeTime=true;return out;});assert(checks.every(x=>x[1]),JSON.stringify(checks));
fs.mkdirSync('/tmp/gachi-street',{recursive:true});for(const [phase,times]of [['curb',[1,30,60,100,145,180,205,225,230,265,300,379,500,750]],['car-board',[1,18,24,28,30,36,44,48,60,77]],['drive',[1,60,120,180,240,299]]])for(const t of times){await p.evaluate(({phase,t})=>{const g=__game;g.resetInput();g.G.freezeTime=false;g.travel(phase);g.step(t);g.G.freezeTime=true;g.G.fade=0;g.render();},{phase,t});fs.writeFileSync(`/tmp/gachi-street/${phase}-${t}.png`,Buffer.from(await p.locator('#game').evaluate(c=>c.toDataURL().split(',')[1]),'base64'));}assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors,screenshots:'/tmp/gachi-street'}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
