const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1100,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:8011/review-train.html?scene=platform&t=0');await p.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('play'));const f=p.frames().find(f=>f.url().includes('?auto=walk'));fs.mkdirSync('/tmp/train-connections',{recursive:true});
 for(const x of [600,720,840,960,1440,1560,1680,1800,1920,2400,3360,3600,3720,3840,4440,4560,4680,4800,4920,5040,5160,5280,5880,6000,6120,6240,6840,6960,7080,7200]){await p.locator('#route').fill(String(x));await p.locator('#route').dispatchEvent('input');await f.locator('canvas').screenshot({path:`/tmp/train-connections/join-${x}.png`});}
 for(const scene of ['intro','platform','boarding'])for(const t of (scene==='intro'?[0,60,143,174]:scene==='platform'?[0,45,90,135,180,225,240]:[0,14,24,36,48,52,68,84,96,108,119])){await f.evaluate(({scene,t})=>{__game.trainScene(scene,t);if(scene==='platform'){__game.G.camX=2400;__game.G.player.x=2705;}__game.render()}, {scene,t});await f.locator('canvas').screenshot({path:`/tmp/train-connections/${scene}-${t}.png`});}
 const checks=await f.evaluate(async()=>{const g=__game,G=g.G,out=[],check=(n,v)=>out.push([n,!!v]);
  g.stage(0);G.freezeTime=true;G.camX=2200;G.player.x=2300;G.waveIndex=2;g.step(1);check('no train before final station encounter',G.train.arrival===-1);G.enemies=[];G.spawnQueue=[];G.player.x=2450;G.waveIndex=3;G.waveActive=false;G.locked=false;g.step(1);check('train starts after station fights',G.train.arrival===0);g.press('use');g.step(241);check('held use cannot board arriving train',!G.train.cinematic&&G.train.arrival===240);g.release('use');g.step(1);G.camX=2400;G.player.x=2715;G.player.z=12;g.press('use');g.step(1);check('airborne use cannot board',!G.train.cinematic);g.release('use');g.step(1);G.player.z=0;G.player.vz=0;g.press('use');g.step(1);check('fresh platform interaction starts jump',G.train.cinematic?.kind==='boarding');if(!G.train.cinematic)return [...out,['diagnostic '+JSON.stringify({state:G.state,x:G.player.x,y:G.player.y,z:G.player.z,arrival:G.train.arrival,gate:G.train.gate,locked:G.locked,wave:G.waveIndex,active:G.waveActive,enemies:G.enemies.length,queue:G.spawnQueue.length}),false]];g.release('use');g.step(35);g.press('pause');g.step(1);g.release('pause');const t=G.train.cinematic.t;g.step(60);check('jump freezes on pause',G.train.cinematic.t===t);g.press('pause');g.step(1);g.release('pause');g.step(120);check('short jump reaches coach checkpoint',G.train.aboard&&G.train.checkpoint===2880&&!G.train.cinematic);
  const {ASSETS}=await import('./js/assets.js');const keys=['nr_platform','nr_platform_front','nr_train_exterior','nr_chad_board','nr_locomotive'];const art=keys.map(k=>ASSETS[k]);try{for(const k of keys)ASSETS[k]=null;g.trainScene('boarding',0);g.render();g.step(121);check('missing arrival art cannot trap progression',G.train.aboard&&!G.train.cinematic);}finally{keys.forEach((k,i)=>ASSETS[k]=art[i]);}
  G.spawnQueue=['nr_tough'];g.stage(0);check('new run resets arrival and pending enemies',G.train.arrival===-1&&G.spawnQueue.length===0);return out;});assert(checks.every(c=>c[1]),JSON.stringify(checks));assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
