const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1080,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8011/review-train.html');await p.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('play'));
 const game=p.frames().find(f=>f.url().includes('?auto=walk'));assert(game);fs.mkdirSync('/tmp/train-final',{recursive:true});
 const scenes=['yard','hall','platform','general','sleeper','pantry','office','conductor','ac','private','roof','boss','boss-roof'];
 for(const name of scenes){await p.locator('#scene').selectOption(name);await p.locator('#game').screenshot({path:`/tmp/train-final/${name}-960.png`});await p.locator('#scale').click();await p.locator('#game').screenshot({path:`/tmp/train-final/${name}-480.png`});await p.locator('#scale').click();}
 const sequences={intro:[0,44,60,90,130,180,230,330,479],boarding:[0,14,24,36,48,52,68,84,96,108,119],'roof-transition':[1,24,48,84,120,180,240,276,324,360,396,419],escape:[1,120,179,210,240,270,290,325,365,445,520,720,850]};
 for(const [scene,times]of Object.entries(sequences))for(const t of times){await game.evaluate(([s,t])=>{__game.trainScene(s,t);__game.G.shake=0;__game.render()},[scene,t]);await game.locator('canvas').screenshot({path:`/tmp/train-final/${scene}-${t}.png`});}
 // Draw every registered actor pose through the same frame loader and blitter used
 // by combat; this catches scaling/cropping differences introduced at runtime.
 const sheets=await game.evaluate(async()=>{const {SPR,getFrame,frameW,frameH,blit}=await import('./js/sprites.js');const names=['tough','bruiser','runner','ambusher','heavy','heavy_unarmed','guard','vikram','vikram_roof'],out={};for(const name of names){const c=document.createElement('canvas');c.width=2048;c.height=224;const ctx=c.getContext('2d');ctx.fillStyle='#253042';ctx.fillRect(0,0,c.width,c.height);ctx.scale(1,1);const poses=[...Array.from({length:2},(_,i)=>['idle',i]),...Array.from({length:8},(_,i)=>['walk',i]),...Array.from({length:3},(_,i)=>['atk',i]),['hurt',0],['down',0],['jump',0]];for(let i=0;i<poses.length;i++){const f=getFrame(SPR['nr_'+name],...poses[i],1);blit(ctx,f,i*128+64-frameW(f)/2,112-frameH(f)+4);}out[name]=c.toDataURL();}return out;});for(const [name,url]of Object.entries(sheets))fs.writeFileSync(`/tmp/train-final/frames-${name}.png`,Buffer.from(url.split(',')[1],'base64'));
 // Live replay through the explorer uses the fixed game update, not timer seeking.
 await p.locator('#scene').selectOption('boarding');await p.locator('#play').click();await p.waitForTimeout(1500);const progressed=await game.evaluate(()=>__game.G.train.cinematic.t);assert(progressed>=60);await p.locator('#play').click();
 assert.deepEqual(errors,[]);console.log(JSON.stringify({scenes:scenes.length,cinematicCheckpoints:Object.values(sequences).flat().length,actorSheets:Object.keys(sheets).length,liveFrames:progressed,errors}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
