#!/usr/bin/env python3
"""Register GPT eight-pose vehicle grids on their wheelbase and road contact line.

Selected sources: market_life/chad_style/{cyclist,rickshaw}_v2.png.
Outputs: market_life/{cyclist,rickshaw}.png and js/delhi_vehicle_art.js.
Uniform scales preserve round tyres and natural adult proportions; no horizontal stretching.
"""
from pathlib import Path
import json
import sys
import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_delhi_life_river as river
from build_delhi_life_market import fit_circle
from sprite_edges import edges
from backdrop_tone import backdrop, plate_light

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'assets/sources/production/stages/dirty_delhi/market_life/chad_style'
OUT = ROOT / 'assets/stages/dirty_delhi/market_life'
PLATE = ROOT / 'assets/stages/dirty_delhi/rebuild/market.png'
HEIGHT = {'cyclist': 156, 'rickshaw': 168}
METADATA = ROOT / 'js/delhi_vehicle_art.js'


def write_metadata(name, data):
    result = {}
    if METADATA.exists():
        source = METADATA.read_text().split('export const VEHICLE_ART = ', 1)[1]
        result = json.loads(source.rstrip(';\n'))
    result[name] = data
    result = {key: result[key] for key in HEIGHT if key in result}
    METADATA.write_text(
        '// Generated by tools/production/build_delhi_market_vehicles.py; 2× cell pixels.\n'
        'export const VEHICLE_ART = ' + json.dumps(result, indent=2) + ';\n')


def trim(a):
    a = a.copy()
    a[a[:, :, 3] < 128] = 0
    a[:, :, 3] = np.where(a[:, :, 3] >= 128, 255, 0)
    ys, xs = np.where(a[:, :, 3] > 0)
    return a[ys.min():ys.max() + 1, xs.min():xs.max() + 1]


def tyre_circles(a):
    """Fit lower tyre arcs, excluding the mudguards and cargo above their axles."""
    mask = a[:, :, 3] > 0
    h, w = mask.shape
    result = []
    for side in (0, 1):
        points = []
        for y in range(round(h * .79), h - 5):
            xs = np.nonzero(mask[y])[0]
            if len(xs):
                points.append((xs.min() if side == 0 else xs.max(), y))
        for x in range(w):
            ys = np.nonzero(mask[:, x])[0]
            if len(ys) and (x < w * .32 if side == 0 else x > w * .72) and ys.max() > h - 20:
                points.append((x, ys.max()))
        result.append(fit_circle(points))
    return result


def build(name):
    frames = [trim(c) for c in river.cells(name, 4, 2, path=SRC / f'{name}_v2.png')]
    circles = [tyre_circles(c) for c in frames]
    reference = circles[0]
    base = HEIGHT[name] / frames[0].shape[0]
    distance = reference[1][0] - reference[0][0]
    registered, fits = [], []
    for a, pair in zip(frames, circles):
        scale = base * distance / (pair[1][0] - pair[0][0])
        b = river.box_scale(a, scale)
        fit = [(cx * scale, cy * scale, radius * scale) for cx, cy, radius in pair]
        # Anchor on the rigid wheelbase midpoint, with both tyres sharing the road line.
        axle = (fit[0][0] + fit[1][0]) / 2
        registered.append((b, axle))
        fits.append(fit)
    half = max(max(axle, b.shape[1] - axle) for b, axle in registered)
    cw = int(np.ceil(half + 3)) * 2
    cw += (-cw) % 4
    ch = max(b.shape[0] for b, _ in registered) + 10
    ch += ch % 2
    strip = Image.new('RGBA', (cw * 8, ch))
    metadata_fits = []
    for i, ((b, axle), pair) in enumerate(zip(registered, fits)):
        x = round(cw / 2 - axle)
        y = ch - 3 - b.shape[0]
        cell = Image.new('RGBA', (cw, ch))
        cell.alpha_composite(Image.fromarray(b), (x, y))
        # Generated interiors are mostly transparent; retain the chain, fork and frame.
        # Runtime spokes turn through those openings behind this detailed generated rig.
        strip.alpha_composite(edges(cell), (i * cw, 0))
        metadata_fits.append([(cx + x + .5, cy + y + .5, radius - 3.5) for cx, cy, radius in pair])
    strip = backdrop(strip, plate_light(PLATE, (0, 200, 1620, 410))[0], level=.7, cast=.3)
    strip.save(OUT / f'{name}.png', optimize=True)
    at = np.median(metadata_fits, axis=0)
    wheel = dict(at=np.round(at, 1).tolist(), r=round(float(at[:, 2].mean() + 3.5) / 2, 1),
                 n=18 if name == 'cyclist' else 12, w=1 if name == 'cyclist' else 1.4,
                 hub=2.5, col='rgba(46,33,23,.95)')
    if name == 'rickshaw':
        wheel['lit'] = 'rgba(176,126,80,.45)'
    data = dict(cw=cw, ch=ch, half=int(np.ceil(max(b.shape[1] for b, _ in registered) / 4)), wheels=wheel)
    write_metadata(name, data)
    print(name, json.dumps(data), 'tyre centre spread', np.round(np.ptp(metadata_fits, axis=0), 2).tolist())
    return data


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    for name in sys.argv[1:] or HEIGHT:
        build(name)
