"""Register the selected injured retreat by pelvis and floor contacts at one scale."""
from pathlib import Path
import json
import numpy as np
from PIL import Image
from build_combat_variety import clean,save_frames,review,largest_component
ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/'assets/sources/production/stages/night_train/rebuild'
def main():
 im=Image.open(SRC/'seth_injured_retreat.png').convert('RGBA')
 rows=[0,345,625,848,1254];xs=[[0,315,590,936,1254],[0,345,590,930,1254],[0,300,618,930,1254],[0,313,627,941,1254]]
 hips=[(145,200),(432,200),(766,190),(1091,214),(155,513),(450,530),(746,520),(1068,518),(132,740),(412,743),(735,740),(1080,735),(172,1130),(480,1080),(805,1070),(1130,1080)]
 scale=184/295 # Reference crown 31 to boot sole 326, matching the established 92px Seth.
 frames=[];meta=[]
 for i,(hx,hy) in enumerate(hips):
  row=i//4;left=xs[row][i%4];top=rows[row]
  c=clean(im.crop((left,top,xs[row][i%4+1],rows[row+1])))
  a=np.array(c);a[~largest_component(a[:,:,3]>24)]=0;c=Image.fromarray(a);bounds=c.getbbox()
  c=c.resize((round(c.width*scale),round(c.height*scale)),Image.Resampling.LANCZOS)
  x=round(160-(hx-left)*scale);y=round(265-bounds[3]*scale)
  out=Image.new('RGBA',(320,272));out.alpha_composite(c,(x,y));frames.append(clean(out))
  meta.append({'hipY':round((y+(hy-top)*scale)/2,3)})
 climb=Image.open(SRC/'seth_injured_climb.png').convert('RGBA');climbs=[];climb_meta=[];cs=184/590
 for i in range(4):
  cell=clean(climb.crop((round(i*climb.width/4),0,round((i+1)*climb.width/4),climb.height)))
  bounds=cell.getbbox();hand=[375,373,373,425][i];x=round(160-244*cs);y=round(265-bounds[3]*cs)
  cell=cell.resize((round(cell.width*cs),round(cell.height*cs)),Image.Resampling.LANCZOS)
  out=Image.new('RGBA',(320,272));out.alpha_composite(cell,(x,y));climbs.append(clean(out));climb_meta.append(round((x+hand*cs)/2,3))
 mpath=ROOT/'assets/frames/manifest.json';m=json.loads(mpath.read_text());save_frames(m,'nr_vikram','injured_retreat',frames,'nr_vikram/injured_retreat');save_frames(m,'nr_vikram','injured_climb',climbs,'nr_vikram/injured_climb');mpath.write_text(json.dumps(m,indent=2)+'\n');review('seth-injured-climb',climbs);review('seth-injured-retreat',frames)
 (ROOT/'js/seth_retreat_anchors.js').write_text('// Generated by build_seth_retreat.py. Logical canvas-space pelvis anchors.\nexport const SETH_RETREAT_FLOOR=132;\nexport const SETH_RETREAT_ANCHORS='+json.dumps(meta)+';\nexport const SETH_CLIMB_HANDS='+json.dumps(climb_meta)+';\n')
 jacket=clean(Image.open(SRC/'seth_jacket.png').convert('RGBA'));jacket=jacket.crop(jacket.getbbox());jacket.thumbnail((136,88),Image.Resampling.LANCZOS);jacket.save(ROOT/'assets/stages/night_train/rebuild/seth_jacket.png')
if __name__=='__main__':main()
